const locations = [
  "Masjid E Latheefia",
  "Satyanarayana",
  "Hanuman Temple",
  "Maisamma temple",
  "Masjid e Hafeeza Shaheen",
  "Muslim graveyard",
  "Masjid-e-Bilal",
  "Sri Annapurna Sameta Kasi Viswanatha Alayam",
  "Shani Temple",
  "Laxmi Narashimha Swamy Electrical and Enginerrings",
  "Masjid-E-Aqsa",
  "Sri Seeta Ramanjaneya Swamy Temple",
  "Sri Akkanna Madanna Devalayam",
  "Raghavendra Kalyana Mantapa",
  "Dargha-E-Ya Ghouse",
  "Masjid Mashak Shah",
  "Sri Jungal Vithoba Devasthanam",
  "Mohammadia Masjid",
  "Masjid E Ghousia",
  "Hazarat syed sha musa qadri RA",
  "Naala Pochama Temple",
  "PothuLinganna Swamy Temple",
  "Syed Ali Masjid",
  "Masjid e Akbari Begum",
  "Sri Renuka Ellamma Temple",
  "MASJID-E-ABUBAKR",
  "Masjid E Qutub Shahi",
  "Masijd sadiyam",
  "SRI KOTA GUTTA PEDDAMMA TALLI TE PLE GAJULARAMARAM",
  "Temple Office",
  "Masjid E Makkah Ummul Qura",
  "Sri Balaji Mandir",
  "Sri Padmavathi Sametha Venkateshwara Alayam",
  "Film Nagar Daiva Sannidhanam",
  "Qudain Masjid",
  "Bharath nagar maharaj youth adda",
  "Subramanyam Temple",
  "Kanakadurga",
  "Bhoolaxmi Temple",
  "Peddama Temple Tarbund",
  "Marlamaissamma temple",
  "Nalacunta",
  "Aghora kali mandir",
  "Masjid E Gada Baig",
  "Chirayala Laxmi Narasimha Swamy Temple",
  "Renuka Yellamma Devi Temple",
  "Shree Jagannath Temple",
  "Art Of Living Manas Ganga Ashram",
  "Sri Shirdi Saibaba Sansthan",
  "Sri Peddamma Temple",
  "Iskcon",
  "Naga Devatha Temple",
  "Sri Shirdi Sai Baba Temple",
  "Shri Durga Mata Alayam",
  "Maisigandi Maisamma Temple",
  "Shri Ram Mandir",
  "Jamy Masjid Sayyedia Umar Farooq Chandanagar Hyderabad",
  "Subramanyeswara Temple",
  "Venkateshwara Swamy Temple",
  "Meharbaba house",
  "Masjid-e-Hanafiya",
  "Marakata anjaneya swamy temple",
  "Masjid-E-Sayeeda Farooqui",
  "Sai Baba Temple",
  "Ambedkar statue",
  "Hanumanmandir",
  "SHIV MANDIR",
  "Sri JalTal Hanuman Mandir",
  "Masjid Jaweed Quadri",
  "Rama Temple",
  "Nakkal Banda Pochamma Temple",
  "mosque",
  "Masjid E Farooq E Azam",
  "Sri Kanaka Durga Alayam",
  "Taramani Temple",
  "GAG General Store (Pooja Items)",
  "sri beerrappa temple",
  "Gandi Maisamma Temple",
  "Santhoshi Matha Temple",
  "Banagaru maisamma",
  "Masjid eSiddiquia",
  "Mothi Masjid",
  "Sri SitaRamanjaneya Swami Vari Alaya Committee",
  "KOTESHWARAALAYAM ANURADHA COLONY",
  "Eidgah Devara Yamjal",
  "Jama Masjid Hazrath-E-Biala RA",
  "Sri Santoshi Mata Mandir",
  "Sri Balanjaneya Swamy Temple",
  "Sri Konda Pochamma Devalayam",
  "Masjid- e-Hashmi",
  "Abdul Rahman Masjid",
  "Masjidemehboob fatima (",
  "Sri Sri Venu Gopala Swamy Mandir",
  "Sri Ram Mandir",
  "Sri Shiv Mandir",
  "Pochamma Temple",
  "Balaji Temple",
  "Sree Veer Aanjaneya Swamy Temple",
  "Mosque",
  "Sivalayam",
  "Nageshawari",
  "Yellama Temple",
  "LORD SHIVJI MANDIR",
  "Masjid-e-Mohammadia",
  "MASJID E BILAL",
  "Pochamma temple",
  "Hanuman temple",
  "Sri Sri Sri Lalitha Naga Lingeshwara Swamy Vari Devalayam",
  "Masjid Mosque",
  "Sri Maisamma Thalli Alayam",
  "Yellamma Temple",
  "Sri Mallikarjuna Swamy and Hanuman Mandir",
  "Masjid-e-Ghousia",
  "Hashmi Masjid",
  "Jamia Masjid",
  "HINDU TEMPLE",
  "Masjid-e-Hazrat Bilal",
  "POCHAMMA TEMPLE",
  "Navabharath Youth Force Ganesh Manddapam",
  "Berappa Swamy Tample",
  "Bhordaie Old City",
  "Masjid e mahboobiya",
  "Masjid-e-Arafat",
  "Durga matha gudi",
  "Masjid-e-Sharfuddin",
  "Masjid e qutub shahi RNs colony",
  "Shiva Temple",
  "Ganesh and Hanuman Temple",
  "Sri Sita Ramanjaneya Temple",
  "Jamia Masjid Ahle Hadees Chilkalguda",
  "Mohammadiya Masjid",
  "Jama Masjid",
  "Markondaiah Temple",
  "Amma Durga Bhavani",
  "Sai Baba",
  "Misamma Temple",
  "Sri SadaShiveshwara Swami Gudi",
  "Masjid Hazrath Haji Miya Sahab",
  "Hanuman Mandir",
  "Vara Siddi Vinayaka Temple",
  "Pajol Boro Jame Mosjid",
  "BURUGADDA TANDA Ganesh Mandapam",
  "Devi Maa Temple",
  "Garuda Temple",
  "Chinna hanuman temple",
  "Yellama temple",
  "Lord Shivalayam",
  "PEDDAMMA TEMPLE",
  "sevalall temple",
  "Dargah",
  "Shivalayam Chennaram",
  "Masjid e Kubra Ahle Hadees",
  "Eidgha Giniyarpally",
  "Lord shiva Statue",
  "Sri Shivalayam temple",
  "Boddu Rayi Chilkoor",
  "Lord Hanuman Temple",
  "Mahankali Temple",
  "Masjid-E-Umar farouq",
  "Masjid E Noor E Ilahi",
  "Mala varipochammadevi temple",
  "Mehbub Subhani Dargah",
  "Maisamma Temple Bansilal nagar",
  "Sri Pochamma Temple",
  "Mosque Masjid-e-Faizul Quran",
  "Sarwarjahan masjid",
  "Masjid Hakeem Luqmaan",
  "VINAYAKA SEVA SAMITHI GANESH MANDAPAM",
  "hanuman temple kolukunta thanda",
  "Mankalamma temple",
  "Sri Prasanna Anjaneya Swamy Temple",
  "Masjid e badri uddin",
  "Masjid-e-quba",
  "Balapur Tombs",
  "SHIVAJI CHOWK",
  "Chinna Pochamma Temple",
  "DwarakaNagar Vinayaka Mandapam",
  "poturaj temple ashramam",
  "Masjid e siddiq e saleheen",
  "Masjid e Munawar",
  "HMT Darga",
  "Mosque Quthubh Shah",
  "Sevalal Temple",
  "Sri Kantamaheshwara Swami Devalayam",
  "SHAKTI YOUTH HAYATHNAGAR",
  "Madrasa e Taleem -Ul- Quraan Hayat Bakhshi Begum",
  "Ammavaru temple",
  "Shri Ram Baksha Mutt",
  "Masjid-E-Mustafa",
  "Masjid-E-Saleheen",
  "Kale Matha Temple",
  "Masjid-e-Mustafa",
  "Ganesh temple near RM store  Kirana",
  "Shivalayam Street",
  "Sri Radhakrishna Temple",
  "Sri Narasimha Swamy Alayam",
  "Sri Vittalnath Mahadev Mandir",
  "Tayabba masjid",
  "Sri Seetharamanjaneya Swamy Devastanam",
  "Sri Kanaka Durga Temple",
  "Sri SitaRama Temple",
  "asdfasfd",
  "Mohammedi Masjid",
  "Masjid-e-Noor",
  "Keroortelangana Hanuman Temple",
  "Masjid Muhammadi (Ahle-Hadees)",
  "Hanuman Tree Temple",
  "Sri Venkateshwara Swamy Temple",
  "maisamma Temple",
  "Masjid Syedna Umar-e-Farooq",
  "Masjid E Noor E Alam",
  "machli Wale dargha",
  "Madina Masjid",
  "Sri vallidevasena sametha subrahmanya multi-temple",
  "Sri Godaadevi Mahalaxmi sametha sri venkateswara temle",
  "Sree Guru Peetam",
  "Masjid e Quba",
  "Yellamma temple",
  "Sangameshwara Swamy Temple",
  "Dhoolpet",
  "Hanuman Temple Paathabasti",
  "Lakshmi Temple",
  "Goddess Nagalaxmi Temple",
  "Ganesh Temple",
  "Vinayaka temple",
  "Jama Masjid Rauzatul Hadees",
  "Shivalyam temple",
  "Masjid Road",
  "Grave Yard Old Masjid",
  "Eedamma temple",
  "Bulaxmi temple",
  "Tarkeshwar kumar",
  "Mallikarjuna Swami Temple",
  "Renuka Yalama Temple",
  "Durga matha temple Bihar basti",
  "Masjid e Mohammadia",
  "Sri Shiva Devalayam",
  "Maisigandi Sivalayam Ramalayam",
  "Muthyalamma temple",
  "Masjid Ek Minar",
  "Mahankaalli Temple",
  "graveyard",
  "Qutub Shahi Masjid Alamgiri Kukatpally Moosapet",
  "Eddamma Temple Turning Junction",
  "Al Nizam jaffer Ahmed Masjid",
  "Jeevanguda Hanuman temple",
  "Bansi Das Baba Mutt",
  "Masjid E Khabab Bin Arth",
  "Masjid-E-Hayath",
  "Ayyappa Temple",
  "Ramalayam Temple",
  "Navagraha Temple",
  "Sri Veerabrahmendra Swami Temple",
  "Champa Darwaza Sri Hanuman Mandir",
  "Masjid-e-Lal Ali Khan Ahl-e-Sunnat ul Jamaat",
  "Sree Kanaka Durga Temple -",
  "Masjid E Habeeb Qutub Shahi",
  "Young Star Youth association",
  "Saibaba Temple",
  "Beerappa Temple",
  "Bonamma Temple",
  "Ramraj Guruswamy Sannidanam",
  "Sri Hanuman Mandir",
  "Katta Maisamma Temple",
  "MASJID-E-ZAITOON",
  "Ek mandhir",
  "Sri Ayyappa Swamy Temple",
  "Masjid e jama hussaini",
  "Maisamma Temple",
  "Sri Bangaru Pochamma Temple",
  "Prasanna Anjaneya Swamy Temple",
  "Sri Padmavathi Venkateshwara Temple",
  "MASJID E REHMANIA",
  "Sri Hanuman Mandir  Bheem Nagar",
  "Tuljamatha",
  "Shri Panchayati Akhada Bada Udaseen",
  "Masjid Miya Misk",
  "Bal Gangadhar Tilak Youth Association B N Reddy Nagar",
  "Masjid -e- mustafa",
  "Madina chicken center",
  "Sri Raghavendra Swamy Temple",
  "SEVEN TEMPLES",
  "Sri Bangaru Maisamma Temple",
  "Anjaneya Swamy Temple",
  "Naga Devatha Devalayam Ambedkar Nagar",
  "BJR Nagar mosque",
  "Masjid-e-Haleemabee Sahiba",
  "Masjid-e-Khairunnisa",
  "Masjid e Omer",
  "Bogaram maisamma thalli temple ABRABOINA FAMILIES",
  "Sree Vasavi Kanyaka Parameshwari Temple",
  "SRI KODANDA RAMALAYAM",
  "Sri Sita Rama Swamy Devalaya Samudayam",
  "Masjid e Basitia",
  "Sri Jagannath Swamy Temple",
  "Durga Temple",
  "Masjid E Mahedavia Daulat Jung",
  "Masjid-e-Rahmat-e-Alam",
  "Konda Pochamma Temple",
  "Masjid Kotla Hasan Ullah",
  "YALLAMMA MAISAMMA GUDI",
  "Lord Gandimaisamma Temple",
  "Masjid E Muhammad",
  "Ramalayam",
  "Siva temple",
  "SHIVALAYAM STREET",
  "SRI KANAKA DURGA AMMAVAARI TEMPLE",
  "Muslim Mosque",
  "Ramanjaneya Temple Nadargul",
  "Charminar",
  "Devasthanam",
  "Masjid-E-Neem Bowli",
  "Shivalayam",
  "Badi Masjid",
  "andole mysamma temple",
  "Mangalath market gandi maisamma temple",
  "DARGAH HAZRAT SYED MOHAMMED YOUSUF HUSSAINI RH",
  "Masjid-e-Hussainia",
  "Shri Seeta Ramanjaya Swami Temple",
  "Masjid E Salehin",
  "Masjid-E-Mohammedia",
  "Durga Devi Santhoshi Mata Temple",
  "Sri Mallikarjuna Swamy Temple",
  "Sri Mallikarjuna Swamy Devalayam",
  "Masjid e mohammedi",
  "Masjid E Mohammedia",
  "Masjid e Faiz Imam",
  "Pochama Temple",
  "Narsagutta Narasimha Swamy Temple",
  "Siddi Baba Masjid",
  "MASJID-E-QALAIGAR",
  "Aai Mataji Temple",
  "Sri Santosh matha temple",
  "Masjid-e-Ittehadi",
  "Ramalayam Shivalayam Temple",
  "Jagannath Temple",
  "Masjid Sarware Konain",
  "Kadtal Braman",
  "Masjid Alamghir Masjid Gadda",
  "Masjid E Noor-un-Nisa",
  "Sri bangaru maisamma temple indiramma colony bowrampet",
  "Rasoolpura Masjid",
  "Sri Vinayaka Templeelevations palm meadows",
  "Masjid E Rizwan",
  "Macha Bolarum Masjid",
  "Chhath Pooja Ghat Bollaram",
  "Ashurkhane Taskeen e Mohammad Asif Nagar",
  "Lord Ganesh Temple",
  "Vemkateshwara Swamy Temple",
  "Gayatri Gyan Mandir",
  "Eidgah",
  "Ganesh temple DD colony",
  "Sri Vijaya Kanakadurga Devastanam",
  "Ammenpur Grama Devatha Temple",
  "Sri Siddhi Vinayaka Temple",
  "MASJID-E-ILAHI",
  "Masjid-e-shareef",
  "Sri Vighneshwara Swamy Temple",
  "SRI ABHAYANJANEYA SWAMY TEMPLE",
  "Masjid e Gadi",
  "Sri veerabhramam gari matam",
  "Masjid e Omar Farooq Salafia Ahle Hadees",
  "Saameeri Panchanana Divya Peetam",
  "Goddess Durga Temple",
  "Masjid -e- noor",
  "Sri Hanuman Devalayam",
  "Sri Ammawari Gudi",
  "SRI LAXMI BHAVANI technical world",
  "Anjaneya swami temple",
  "Santoshi Mata Devi Temple",
  "Hanuman Vyamshala beside Muthyalam templeNew Blocks Bolarum Bazar",
  "Rama Mandir",
  "Swayambu Anjaneya Swamy Temple (Hanuman Temple)",
  "Jill Subhani Dargah",
  "Masjid-E-Noor",
  "HANUMAN TEMPLE",
  "Masjid e rahmatul lil alameen",
  "Masjid e Osmania",
  "Ganpati temple",
  "Sri Kanta Maheshwara Swamy Temple",
  "Sri Devi Naga devatha",
  "Swami vivekananda ganesh mandapam",
  "Bhavani matha temple",
  "lalbaba temple",
  "Jalpally KALIWALE TEMPLE",
  "Kandkoor masjid",
  "Sri Mathsya Kurma Sametha Sri Lakshmi Narayana Swamy Dhamam",
  "Medicover Prayer Hall (Masjid)",
  "Katedhan Hanuman Temple",
  "Peddama Temple Khazipally",
  "Masjid E Omer Farooq",
  "Madina Masjid Road Hassan Nagar",
  "Hari Hara Devi Temple(Lord Sriram Lord Shiva)",
  "Hafizpet Dargah",
  "Old Ghouse-e-Pak Flag",
  "Sri Pattabhi Setharamula Kalyana Devasthanam",
  "Katta Maisamma temple",
  "Masjid e Atiya Shakir",
  "Hanuman and Shiva Temple",
  "Radha Krishna Temple",
  "Peddama Temple Kondakal",
  "SRI NALLA POCHAMMA Temple",
  "KattamysammaTempul Bhadurguda",
  "NalaPochamma Devalayam",
  "Sri Ujjaini Mahankali Temple Sikh Village",
  "Ganesh Temple Sri Ram Nagar Sikh Village",
  "HMT TEMPLE",
  "Sita Rama Temple",
  "Masjid E Mohammadia",
  "Narsingh Bhan temple",
  "Kistareddy colony ganesh",
  "Sri Sai Baba Sri Ramalingeshwara  Sri Datta Mandir",
  "Masjid-E-Hamza Ahle hadees",
  "Sri Tuljabhavani temple",
  "Tri Shakti Aalayam (Trishakthi Temple)",
  "Sai Baba Temple Kowkoor",
  "Sri Pochamma temple",
  "SHIVALAYAM",
  "Sri Vijaya Gayatri Seva Samstha",
  "Sailani Baba Dargah",
  "Mahadevpur Colony Ganesha Mandapam",
  "Sri Vanadurga Sri Raja Rajeshwari Sametha Sri Chandramoulishwara Swamy Mandiram",
  "Sri Ranisati Dadi Mandir",
  "Sri Abhaya Anjaneya Swamy Devalayam",
  "Sri Bhulaxmi temple",
  "Jama Masjid Rahmania Mankhal",
  "Sri Uttaradi math Malkajgiri",
  "Shiva temple",
  "Masjid E Rahaman",
  "Pochamma Mahankali Temple",
  "Shri Bhagyalaxmi Mandir",
  "Kambal Posh Masjid",
  "Sri Ramakoti Stupalayam temple",
  "Hanuman Temple Royal Colony",
  "Kizra majid",
  "Sri Nalla Pochamma Temple",
  "MASJID-E-NOOR QUBA",
  "Radha Krishna Temple NISA",
  "Sri Mahankali Temple Mudfort",
  "Bhajana mandiramu",
  "Ellamma Gudi",
  "AMMA DHYANA MANDIRAMU",
  "Shia Masjid Chilla Maula Ali",
  "Masjid e Rashideen",
  "Masjid E Ar Razzaq",
  "Mysamma Temple",
  "Bhavesh youth association",
  "Bhagavadramanuja Sevashramam",
  "Masjid-e-Ikhlaas (Ahle Hadees)",
  "Rajarajeshwari Mandir",
  "Kanakadurga Temple",
  "H",
  "Sri Pochamma Thalli Alayam",
  "Ammavari Devalayam",
  "Vijaya Ganapthi",
  "MASJID AL-RAHMATH  ISLAMIC CENTER",
  "masjid e dawatul islam",
  "Shri Raghunath Temple",
  "Ram mandir or Ramalayam temple",
  "Masjid E Osmane Ghani",
  "Srinivas",
  "Bandi vari palem",
  "Sree Veeranjaneya Swamy Temple",
  "Tulja Bhavani Temple",
  "JMD Guru dharbar",
  "Sri Patala Hanuman Temple",
  "masjid e ahmed quadri",
  "Masjid Abbasia",
  "Masjid E Zaal Saif Sayeed",
  "Sri Maisamma Temple",
  "Santoshi Matha Temple",
  "Sri Mahakaleswar Temple",
  "Mata shrine",
  "mount shamballa book stal",
  "Sri Shivalayam",
  "Sri Siddhi Vinayaka Mandir",
  "Sri Ganesh Sai Baba Daathateraya Devasthanam",
  "hanuman temple hemajipur",
  "Masjid Al-Quba",
  "Masjid-E-Bilal",
  "Sri Laxmi Ganapathi Devasthanam RTC COLONY",
  "Masjid E Jalal kuncha",
  "Ghousia E Masjid",
  "Sulaimani Masjid",
  "Anjaneya swamy temple",
  "Shri Raja Rajeshwari Devalayam",
  "ganapeswara temple",
  "Shree Siddhi Vinayak Mandir Ghansi Bazar",
  "Suraj Bhavan",
  "HINDHU TEMPLE (ts high court)",
  "Masjid-e Moti Begum",
  "Masjid-e-Omer Bin Khattab",
  "Sri Ramanjaneya Swamy Temple",
  "Devendar Nagar Santh Sevaalal Maharaj Temple",
  "SHWETHA NAAGAMMA KSHETHRAM",
  "Pochamma Basthi Khaman",
  "Masjid-E-Kaharwaah",
  "Masjid-e-Sahaba",
  "Sri Spatika Lingeshwara Swamy Devasthanam",
  "Shivalayam Temple",
  "Lord Venkateshwara Temple",
  "POLICE JEEVENDER REDDY FUNCTION HALL",
  "Sri Sai Baba Mandir (Temple)",
  "Yellamma Thalli Devalayam",
  "Tulija Bhavani Temple",
  "Sree Laxmi Narsimha Swamy Traders",
  "Osmangunj Masjid",
  "Old temple shrine",
  "Masjid-E-Ahmad-E-Noor",
  "Sakthi Ganapathi Temple",
  "Madina Masjida Girmapur",
  "Beerappa temple",
  "Katta maisamma temple",
  "Hamidul Islam",
  "Devi Gudi",
  "Ganesha Mural",
  "Sai Baba Mandir",
  "Ayodhya",
  "Faqrunnisa Masjid",
  "MASJID E MUTAHARA",
  "Sri Mahankali Temple",
  "Kanaka Durga Temple",
  "Sunnipura Masjid",
  "Masjid e Qasim Ali",
  "Masjid-E-Ayesha",
  "Masjid Hazrat Bilal",
  "Masjid-e-Hyderguda",
  "Sri Anjaneya Swami Temple",
  "Eidgah  grave yard",
  "Sri Anjaneya Swamy Temple",
  "Qutub shahi mughbara in adibetla road bongloor rangareddy dictates telangana",
  "Bollaram Ganesh",
  "Sri Raja Rajeshwara pooja samagri",
  "Sri Venkateshwara Perumal Temple",
  "Masjid Al Bugdad",
  "Maisamma and Pochamma Temple",
  "Masjid-E-ek khana",
  "Masjid-E-Shah Lagan Sahab",
  "Sharda Temple",
  "Sri Sharada Chandramoulishwara swamy devalayam",
  "Sri Sri Sri Soubhagya Durga Mandir",
  "Bangaru pochamma temple",
  "mutyalamma Temple",
  "Sri Mavirala Yellamma Devalayam",
  "Sri Mahavidya Peetam",
  "Masjid-e-Madina",
  "Masjid-e-qasim",
  "Nizamuddin Mosque",
  "Vankataswara swami temple",
  "Sri Sri Balaji Sridevi Bhudevi Mandir  managed by ISKCON",
  "Veer Hanuman Gowshala",
  "Sri Gandi Hanuman Mandir",
  "Masjid Shahid Mustafa Ahmed",
  "Mallikarjuna Swamy Temple",
  "Abhaya Anjaneya Swamy Temple",
  "Sri Nageshwara Devalayam",
  "MASJID E BUREEDI",
  "Temple of Lord Shiva Parvathi",
  "srinivasa temple",
  "shaik hussain masjid",
  "HAZRAT SYEDMAHABOOB ALI BASHA DARGHA BAHADURGUDA",
  "Road view",
  "Peddamma Temple",
  "Masjid e Azeema Begum",
  "Sri Mahakaleshwar Mandir",
  "Bilal masjid Rehmath nagar",
  "Nagendra Temple",
  "Pochamma thalli temple",
  "Shiva Ganesh Committee",
  "Masjid - E - Rahmania",
  "Sri Kasinarmadeshwara Swamy Aalyam",
  "Jubilee Hills Mosque and Islamic Centre",
  "Sri Panduranga Swamy Temple( RUKAMAYEE TEMPLE)",
  "HAZARAT MUKEH SHAHAZAD",
  "MASJID-E-ARSHAD",
  "tuljabhavani temple",
  "Sri Lakshimi Ganapathi Temple",
  "masjid e bilal allwyn colony",
  "Hanumanth Temple",
  "Masjid e Laeeq unnisa",
  "Hz Bandagi Miyan Shahe Nusrat RH",
  "Manikeshwari Matha Ashramam",
  "Firdous Masjid",
  "Arya Samaj Kurmaguda",
  "Masjid-E-Quadria",
  "Masjid-E-shah Waliullah",
  "Jama Masjid Haza Sultanpur",
  "Masjid Musaib Bin Umair Raziullahutalah",
  "Miskeen Shah Baba Dargah",
  "Masjid e Maryam",
  "SRI SRI SRI RENUKA YELLAMMA TEMPLE",
  "Nav Jyothi Panchsheel Durga Mata Mandir",
  "Mallana swami temple",
  "Bahadurguda Muslim graveyard",
  "HANUMAN TEMPLE BODAJANAMPETA",
  "SP",
  "Nalgonda Old City Kotamisamma Temple",
  "Masjid e Ibrahim",
  "Sri Malikarjuna Swamy Devalayam",
  "Sri Sri Pochamma Thalli Alayam",
  "Pochamma Thalli Temple",
  "Imam bowli masjid",
  "Bangaru Maisama Temple",
  "Jamia Masjid - E - Azizia",
  "Durgamatha temple",
  "Merama Yadi Temple",
  "Mugni mazhari sahab",
  "Venkateshwara Devalayam",
  "Arshad pasha Qaudri home Al haq colony",
  "Sree sidhi vinayak temple BJR NAGAR",
  "Pochamma Temple Gandiguda",
  "Old mosque",
  "Masjid-e-Aisha Zahoor",
  "Sri Bangaru Misamma Ammavari Sannidhi",
  "Sri Nalla Pochamma Ammavari Sannidhi",
  "Masjid Ahmad",
  "Ibrahim Masjid",
  "Sri Katta Maisamma - Pochamma Temple",
  "Jamel-Bin- Osman",
  "majid-e-Rehmate ilahi",
  "Sri Gopala Venkateshwara Swami Temple",
  "Shri Mallikarjuna youth",
  "Sri Renuka Yellamma Devalayam",
  "Masjid E Petla Burj",
  "Bangilstore",
  "Sri Renuka yellama Thalli temple",
  "JABRIMARFA",
  "Dattatreya swamy Temple",
  "Sri Sitaramanjaneya Swamy Temple",
  "Markatha Panchamukhi Shivalayam (Spatika Narmada Banalu Panchaloha Lingalu)",
  "Sree Radha Krishna Mandir",
  "Masjid-E- Himayathul Islam",
  "Shivamander",
  "Masjid E Raza E Ilahi",
  "Masjid-e Al-Fatah",
  "Peddamma Bhanda",
  "sri Brahmarambika mallikarjuna temple Kardanur",
  "Bali Peetam Alayam",
  "Shri Bhooteshwar Mandir  Shri Narayana Ashram",
  "Masjid E Zainab",
  "Masjid E Afsar Jung",
  "Pochamma thalli Temple",
  "Ayappa Temple",
  "Masjid Owaisi Hospitals",
  "Balanjaneya Devalayam",
  "Masjid-e-Mahdavia",
  "vankateswara swami temple",
  "Masjid-e-Ameer Khairunissa",
  "Bangaru maisamma temple",
  "Masjid-e-Hyderia",
  "Sri Pochamma Devalayam",
  "Birachi Narayan jati Sanjay Kumar jati",
  "Shri Shani Shakti Dham",
  "Mazar -e-Shareef Mirasha Quadri",
  "Hazrath Qutubuddin Shah Dargah",
  "Masjid e Hussain Meeran",
  "Devuni Gutta Sridevi bhudevi sametha Srivenkateswara swamy temple",
  "Sri Raghavendra Swamy Mutt",
  "Masjid-E-Sardar-E-Rabiya Malkajgiri",
  "Masjid E Mohammdia",
  "Sri ganesh tiger youth",
  "Tulja Mata Temple",
  "Sri Laxmi Mata Mandir  Gandhi Bhaitak",
  "Sri Datta Mandir Beerban Bagh",
  "Nalla Pochamma Temple",
  "Bommakanti Sravan",
  "Gajala papama temple",
  "Shiva Parvati with Ganesh n Subramanyam Swamy",
  "Sri Baktha veera anjaneya temple",
  "Masjid E Ismail Faroqui",
  "Masjid Shamima Farid",
  "Yellamma temple raikal shadnagar",
  "Manchirevula Lord Shiva Temple",
  "chowdamma temple",
  "Darga khalij khan",
  "Dadu Mandir",
  "Meenakshi Amma",
  "Mata temple",
  "Sri Sheetala kali Mata Devalayam",
  "Durga Matha Temple",
  "Masjid Habibia Nearest Masjid To Mindspace",
  "Masjid E Tawheed",
  "Sree Pochamma Sahita Vijaya Durga Devi Temple",
  "Masjid-e-Hasan",
  "Masjid-e-Khizra",
  "Laxmi Narasimha Swamy Temple",
  "Venkatesh",
  "Sri Ramalayam",
  "Masjid e afzal yaseen",
  "Masjid E Haleema",
  "KATAMAYYA TEMPLE",
  "Durgamma Temple",
  "Venkateshwara Temple",
  "Masjid Ebadullah Shah",
  "Masjid-e-Shahzadi Begum",
  "Sri Sahasralingeswara Swamy Devastanam",
  "Sri Nalla Pochamma Alayam",
  "Mahakali Mata Mandir",
  "Shri Shirdi Sai Baba Temple",
  "vinayaka temple",
  "Masjid e Firdous",
  "Mallangudetemple At Kaziduga",
  "Sree Krishna Mutt",
  "Shiva Giri",
  "Sri Kheteshwar Temple (Bhavan)",
  "Maisamma Ammavari temple green homes colony",
  "Sri bhulaxmi amma temple",
  "Kinnara maisamma temple",
  "Maha Panchayatana Devalayam",
  "New Sri Hanuman Mini Transport",
  "Jamia Masjid Saheb Nagar",
  "MASJID E MOHAMMADIA",
  "SRI LAKSHMI KUBERA TEMPLE",
  "Sri katta maisamma temple",
  "sri kamarathi beerappa temple",
  "Masjid-e-Aqsa",
  "KATTA MAISAMMA TEMPLE BHUDEVI HILLS",
  "Eidgah Tondpally",
  "Akbari Masjid",
  "Masjid Ibrahim Sarvari",
  "Sri Vinayaka Mandapam",
  "Masjid-E-Hussaini",
  "Swaraj Nagar Masjid",
  "Masjid E Kareem",
  "MAJID-E-KAZAM",
  "Bahmani Golconda Jama Masjid",
  "Bahaddurpura",
  "Balapur Ganesh",
  "Sri Manikanta TempleBk Guda Park",
  "Masjid Al Geelan -",
  "Masjid-E-Mohammed Haji Ismail",
  "Masjid e Top Khana",
  "Masjid-e-Haneef",
  "Guruvayur Sri Krishna Mandiram",
  "Masjid E Azizia",
  "Kali Mandir",
  "Masjid e Ali Murtuza",
  "SRNagar Peddamma Talli Temple",
  "Masjid-E-Himayat Sagar",
  "Masjid-e-Firdous",
  "DBS Ganesh Mandapam (Attapur)",
  "Masjid Buqari",
  "Masjid E Sameena Firdous",
  "Hazrat Dargah Jeete Peer",
  "Siva Narayana Devasthanam Koneru",
  "Hanuman Temple  shivalayam",
  "Masjid E Meer Salaabat Ali (MZK)",
  "Sri Maisamma Talli Alayam  Mushk Mahal",
  "Masjid E Khatija Abdul Khader Qureshi",
  "Ganesh utsav samithi",
  "Madinaguda Madarsa",
  "masjid-e-haza  shasha pahadi",
  "Sangareddy Malkapur X road sheshadri Nagar colony",
  "Jai hanuman baktha samajam Indiramma colony Manchirevula",
  "Sri Lakshmi Narasimha Swamy Temple",
  "Ayyappa Swamy Temple",
  "MASJID E ZULFIQHAR PUPPALAGUDAJAMIA MASJID PUPPALAGUDA",
  "Masjid-E-Ibrahim Gulshani",
  "Sri Beerappa Swamy Alayam",
  "Thummaloor pochamma temple",
  "Masjid-E-Qubool Pasha",
  "Sri Kanaka Durga Devi Sri saraswathi temple",
  "LUCKY KINGS YOUTH MANDAPAM",
  "Sri Sri Kota Maisamma Temple",
  "Masjid-E-Arqam",
  "MASJID-E-MUHAMMADI",
  "Bal Amma Temple",
  "Masjid-e-Ibrahim (Ahle Hadees)",
  "Masjid-e-Abubakkar",
  "Masjid-e-Ayesha",
  "Sri Durga Malleswara Swamy Temple",
  "Sri Lakshmi Ganapati Temple and God Shiva templeNava Grahalu N Hanuman temple",
  "Kali wala mata temple",
  "Jama Masjid Chilkur",
  "Musalla Haseen Pasha",
  "Darga",
  "Masjid-E-Ahle Sunnat gunbazar",
  "Sri Sidhi Budi Vinayaka Swamy Temple",
  "Kali Masjid (Masjid-E-AbaedaLateef )",
  "Shiva Temple Bairagi Guda",
  "sri swayambhu abaya anjaneya swamy devasthanam",
  "sri Veeranjaneya Swami Temple",
  "Dhurgamma temple",
  "Birappa Temple",
  "Narsimha Swamy Temple",
  "Ganesh Temple - Sri Ganesh Uthsav Committee",
  "Sri Siddhi Vinayaka Devasthanam",
  "Dargah (Chillah)",
  "Sri Vidya Ganapathi Devalayam(Temple)",
  "Masjid-E-Mohammedia ( Ahle Hadees)",
  "Masjid E Jamaat Ul Muslimeen",
  "Shirdi Sai Baba Temple",
  "MQ Dreams Masjid Musalla",
  "Jama Masjid-e-Qutub Shahi",
  "Sri Raja Rajeshwara Temple",
  "Kalimatha Temple",
  "Seetharamanjaneya Temple",
  "LMA Temple",
  "EIDGAH OF MALLEMPET",
  "Arjun galli",
  "Sri Venkateshwara Swamy Mandir BDL Township",
  "Idgah",
  "omkara kshethram annojiguda",
  "Hanuman Temple Sannidanam",
  "Hindhu Temple",
  "Shri Pandarinath Temple",
  "Masjid e osman e ghani(RZ)",
  "Masjid-e-Mukarram Jah",
  "Lord ganesha Temple",
  "Shri Hema Durga Sahasra Lingeswara Swami Temple",
  "Hanuman Temple Macha Bolarum Select Talkies",
  "Masjid E Faizul Islam",
  "Syed Ali Shah Sahab Qibla",
  "Masjid e Noorani",
  "Masjid E Khadim",
  "Sri laxmi Narasimha Swamy Temple",
  "Sri Kanaka Dhurgamma Gudi",
  "Sri Seetala Bhavani Devi Temple",
  "Peddammatalli Temple",
  "Sai baba colony Sai baba temple",
  "Sky Blue Friends association",
  "Sri lakshmi ganapathisri sitha ramanjeneya swami devastanam",
  "PEDDAMMA TEMPLE Indra Reddy Nagar",
  "Beerappa Swamy Temple",
  "sri anjaneya Sahitha Shivalayamu",
  "JAMA MASJID MUTHANGI X ROAD",
  "Masjid e raheema",
  "Masjid E Sang (Patthar Ki Masjid)",
  "Durga Maa Temple",
  "Peerla masjid",
  "Sri Laxmi Narasimha Swamy Temple",
  "Sri Mahankali Pochamma Temple",
  "Mohammida Masjid",
  "Nagamma Temple",
  "Peddakanjerla Masjid",
  "Vijaya ganapati jyotishyalayam",
  "Masjid-E-Mahadavia",
  "Sri laxminarasimma temple",
  "Sri Venkateswara swamy Venkanna gutta",
  "Sri Veerabhadra Swamy Temple",
  "Khasimpoor Masjid",
  "Adarsha Colony Pochamma Devalayam",
  "Masjid Hafez Mohammed Ali Khan (Bait-Un-Noor)",
  "Raising Stars friends( Santhana Maha Gapathi kakaguda)",
  "Hindu Goddess Chowdeswari Devi Temple",
  "Bangaru Maisamma Temple",
  "Masjid Chiraan palace",
  "Kasi Bugga Shiva Temple",
  "Shree krishna temple",
  "Masjide-E-Qutub Shahi Near Bachpan school boduppal",
  "Sayeeda masjeed Nalgonda",
  "MASJID E MOHAMMAD OSMAN",
  "MASJID-E-Gafariya",
  "Masjid-e-Qubur",
  "Sri Abhayanjaneya Swamy Temple",
  "Sri Siddaji Appa Mandir",
  "Sri Ammavaari Gudi",
  "MASJID E NOOR",
  "Pochama Temple Kaman",
  "Shri Hanuman Devalayam Ambedkar Nagar",
  "Jai shriram",
  "Masjid-e-Aisha",
  "Masjid e Khaja Bi",
  "Madarsa Bahar-e-Madina",
  "Sri Kalyana Rama Chandra Swmy Vari Mandiram Reddy Gudem",
  "Chitragupta Devalayam",
  "Masjid e Karim Ullah Hussaini",
  "Sri Chandrala Parameshwari Temple Nadergul",
  "Vinayaka Hanuman Temple",
  "Mazaharuloom Madarsa",
  "Old Hanuman Temple",
  "Upasani Baba Tekri",
  "MASJID E KHALEEL",
  "Masjid -e- Maryam Sayeed Saif",
  "Kohe ghar e moula ali",
  "Gajula Uttam kumar",
  "Sri Baktha Anjaneya Swamy Devastanam",
  "t",
  "Sri Kasi Viswanadha Temple",
  "Jama-e-Masjid Mohammadia",
  "Masjid -E-Raahath",
  "Muthyalamma Temple",
  "Jamia Masjid Ahle Sunnat Wal Jamat",
  "Masjid Ghouse-e-Azam",
  "Masjid E Bilal",
  "Sri Renuka Ellammathali Goshala",
  "Krishna",
  "Sri Edamma Temple",
  "Masjide Asma Mohammadiya",
  "Sri Hanuman Temple",
  "Markandeya Swami Temple",
  "Samsthan Shri Bhatji Bapu Bagh",
  "Maha Jageshwara Temple",
  "Masjid Bagh Burq Jung",
  "Masjid Qutubshahi",
  "Syeda afzal begum saheba",
  "IBRAHIM MOSQUE (GOLCONDA)",
  "Ellamma Temple",
  "Hazrath asadulla Sha qhadree dargah Shareef gundram pally",
  "Thiru Tulukanthamma temple",
  "Masjid -E- Osmania",
  "Sri Shiva Temple",
  "Shri Pochamma Talli Devalayam",
  "Chidamber home hyderabad",
  "Sri thatimaisamma temple",
  "Dargah-E-Shareef",
  "Masjid E Ghansi Bazaar",
  "Mir Saber Ali Zawar Masjid  Bargah E Masoomeen as",
  "Masjid e Haji Kamal",
  "Aziz Jung Masjid",
  "Yaapa Chettu CIB Quarters",
  "Hazrat Lalan Masjid",
  "Pochama temple MALA",
  "Jamia Majid Complex",
  "Sri Mallanna Swamy Gudi",
  "Kotamysamma Tempul bhadurguda",
  "Sri Sri Maisamma Thalli Devalayam",
  "Uppalamma Temple",
  "Mysamma Temple Lingaram",
  "MASJID E NOOR (WESTERN PROVINCE)",
  "Veeranjaneya swamy Temple",
  "Habeebia Masjid",
  "Veera Anjaneya Temple",
  "Syed Abdur Razzaq Saheb Masjid",
  "Masjid-e-Kareem",
  "Masjid-e-Mehboobia",
  "Aasramam",
  "Jamia Ahle Sunnah wal Jamaa",
  "Mohammedia Masjid",
  "Nagamma devalayam",
  "kistareddypet EIDGAH",
  "Syed subhani",
  "HANUMAN YOUTH ASSOCIATION",
  "Akkana Madanna Temple",
  "Ravirala AshurKhana-e-Nalsab",
  "SRI PERUMANDLA HANUMAN TEMPLE",
  "Pochamma Temple Korremula",
  "Ram sena youth association mansanpally",
  "Sri Panchamuka Anjaneya Swamy Vari Sannidhi",
  "Sainath mandhir",
  "Sri Edama Temple BTN",
  "Masjid-E-Hazrath Syedna Omer Farooq",
  "Sky Association",
  "Lord Shiva Temple",
  "Masjid E Mohi Uddin",
  "Shankar Goud Colony",
  "pochamma temple",
  "Masjid E Mohammedia Old Masjid",
  "Beerappa swami temple",
  "Sri Sri Nalla Pochama Temple",
  "MADURASANAMA TEMPLE",
  "Muthyalammanalla pochamma temple",
  "Madinaguda Dargah",
  "Masjid-E-Haneefa",
  "Pochamma Temple Mall",
  "Edgah",
  "Kafara",
  "Sri lakshmi Ganapathi Assocestion",
  "Sree Hanuman Temple",
  "Sri Beerappa Temple",
  "Sri Sri Sri Lalitha Tripura Sundari Devi Temple",
  "Renuka Mandir",
  "Phool Hanuman",
  "hanuman temple osmanpura",
  "SRI NALLA POCHAMMA TEMPLE",
  "Masjid DARGHA MAROOF ALI SHA Sahab",
  "Maisaamma temple",
  "Mallanna Temple",
  "Masjid Nasser Saleh bin Hamoudesh",
  "Sri Shakti Ganapathi Devalayam",
  "Fezan e Mustafa Masjid",
  "Aai mataji bader",
  "Masjid-E-Noorani",
  "NTR Colony Masjid",
  "Masjid E Mecca",
  "Jama Masjid Humayun Nagar",
  "Sant Sevalal Temple",
  "Vaddera Edamma Devalayam",
  "Bajrangdal ganesh",
  "MASJID-E-DARUL AMEEN",
  "Shivalayam Dwajastambam",
  "Hanuman and Sai Baba Temple",
  "Veeranjaneya temple potlapahad",
  "Jai Sri Mannarayana Hari Au",
  "Sri Shiva temple",
  "Hanuman Temple Ganesh Mandapam",
  "Masjid-E- Syed Anwar Hussain  Madrasa Islamia Hafeezul Uloom",
  "Idgah Ground",
  "Qizra Mosque",
  "Sri Venkateswara Swamy Temple",
  "Sri Bramaramba Mallikarjuna Swamy Temple",
  "Choti masjid hameedullah nagar",
  "Nala Pochamma Mandir",
  "Madanna",
  "Masjid-e-Burhane Shah Sahab",
  "Masjid E Kamaan",
  "Masjid Al Kausar",
  "Masjid Sadiq Zaheeruddin",
  "Masjid e Roshan",
  "Sri Durga Mata Mandir",
  "Sri Anjaneya Swamy Devalayam",
  "Masjid E Shamarok",
  "Pantul poojari",
  "Nava Chaitanya Youth",
  "Muslim graveyard khabrasthan Jalpalli",
  "Sri Kanaka Durga Mahalakshmi Temple",
  "Ganesh Yuva Sena",
  "GOUSE-E-AZAM DARGA SHARIF SUBASH NAGAR",
  "Sri Yellama Devalayam",
  "Temple Entrane",
  "MEHABOOB SOBANI DHARGHA",
  "MuthyalammA Temple",
  "Vinayaka Temple",
  "Sri Mahadev temple",
  "Sree Venu Gopala Krishna Swamy Temple",
  "Tek Sri Hanuman Temple",
  "Royal Mas bhagyam Masjid public Garden",
  "masjid-e-munshi sahab RH",
  "Durga Mata temple Laxmi Nagar colony Village Laxmiguda",
  "Kumawat samaj trust",
  "Muslims khabrastan",
  "masjid e mohiuddin sahab",
  "Lb Nagar Kaliwale Temple",
  "Shiv Temple",
  "Temple located",
  "Sri Laxminarayana Temple",
  "Masjid Malik Dana",
  "()",
  "Jama Masjid E Osman",
  "KALYANA VENKATESHWARA SWAMI",
  "Sri Veerabhadra Swamy sahita Mahankaleshwara Swamy",
  "Masjid E Budhan Saheb",
  "Masjid E Markaz ul Irshad",
  "Masjid -E-Noor",
  "Koneru",
  "Sree Laxmi Venkatesh",
  "Garudagallu",
  "Masjid e madina munawwara",
  "Masjid E AL-Malik",
  "Durga Devi Temple",
  "SRI ABHAYANJENAYA SWAMY DEVASTHANAM",
  "Mandiram",
  "Masjid Abubakar Siddiq",
  "Sri TULJA DURGA BHAVANI MATA TEMPLE",
  "Durga Bhavani Temple",
  "Masjid Irshad",
  "Sonte Peer Dargah",
  "Masjid-e-Shameem",
  "Masjid E Kamargah",
  "Hindu Temple",
  "Mandir Kumawat",
  "Lingareddy pally",
  "Goddess temple",
  "Sri Pochamma Talli Devalayam",
  "Jama Masjid csk",
  "Sri Ramalingeshwara Temple",
  "Shree Muralidhara Temple",
  "Jai Durga Bhavani Temple",
  "Pochamma Temple sanjay gandhi nagar",
  "Masjid e rahimiya",
  "Girinagar Masjid-e-Hussaini",
  "Naaga Matha",
  "Darvesh Masjid",
  "EDGA chitkul",
  "Sri Ayyappaswamy Temple",
  "Beerappa Mallikarjuna Swamy Temple",
  "masjid-e-saleheennavaranguda",
  "Masjid-E-Sulthan Bagh",
  "Masjid Waqar Unisa",
  "Hindu Shmashana Ghat",
  "Masjid e Ghulam Nabi Shah",
  "Masijd-e-quba",
  "Tulja Bhawni Temple",
  "Shiv temple",
  "Al Rehman Masjid ahle hadis",
  "Masjid-e-jalaluddin",
  "Ram GirihillsGuffa NagarHyderabadTelangana",
  "Sri Murlidhar Mandir",
  "Masjid e mehmoodia",
  "Pushkarini",
  "Yadagiri anna prasadam hall",
  "Masjid Abul Hasnat",
  "Sai Baba temple",
  "Choti Masjid",
  "Kamaldham Mandir Lotus Temple",
  "Maisamma TempleMuthylabaghHyderaguda",
  "Majlis Tameer-e-millat",
  "Masjid E Noor Mohammedi",
  "Temple of Ganesha",
  "Cellar Namaz Musalla",
  "Masjid E Burhan",
  "Gandimaisamma Thalli Temple",
  "Jamia Nizamia Masjid",
  "Navadurga temple ghatkesar",
  "Masjid E MOHAMMADIA ahlesnnt wl Jmt",
  "MASJID-E MADINAH-TAYYABAH",
  "Gowdavalli Mallanna Temple",
  "MASJID ZAINAB",
  "Sri Venkateshwara Devasthanam",
  "Sri Hanuman Mandir Hanuman Vyayam Shala",
  "BogulKunta Masjid",
  "Islamic Center Masjid E Sabiha",
  "Sri Mallanna Swamy Devalayam",
  "Ramulavari temple",
  "Sai baba temple road",
  "Emani Vamsi Temple",
  "Bajarang dall",
  "Sri Kanak Durga Devalaya",
  "Dr Nazar Mehboob Shah Quadri RH Dargah",
  "Masjid -E- Khadijatul Kubra - Ahle Hadees",
  "Sri Devi Nalla Pochamma Devasthnam",
  "Vattepally temple",
  "Nagar Pati Hanuman Mandir",
  "Sri Kanchi Kamakshi Ammavari Devalayam",
  "Bongloor",
  "Aryasamaj Mandir Sharbangla",
  "Amina Masjid",
  "Masjid E Jaame Darul Quran",
  "Juma Masjid",
  "Marakatha Sri Lakshmi Ganapathi Temple",
  "Shree Siddhivinayak Ganapati Mandir",
  "Qutub Shahi Masjid",
  "Kota Maisamma Temple",
  "Sri Anjeneya Temple",
  "Sri Sanjeevani Abhaya Anjaneya Swamy Temple",
  "Kollur ballama temple",
  "Sri RajaRajeshwara Swamy Temple",
  "Mohammedia masjid  Abdul Kareem",
  "Durga Amma Temple",
  "Masjid-e-Ahmedia",
  "Lord Shiva and Hanuman Temple",
  "Muneerabad peddamma temple",
  "Diamond Systems",
  "Troop Bazaar Mosque",
  "Hanuman mandir",
  "Pochamma And Durga Bhavani Temple",
  "Ellamma Temple Lanco Hills Manikonda",
  "Sri Hanuman Temple Balaiah Nagar",
  "Masjid-E-Arafath",
  "Razaa gali",
  "Muhammadia mosque",
  "Darga Hazrath Syed Shah Sarwar muhammed Quadri RH",
  "Sri Durga Yellamma Thalli Devalayam",
  "Masjid-E-Ghousia Gulshan",
  "Shivalayam - Sahara Estates",
  "Masjid E Muhammadia Asj",
  "Pochamma Temple Annojiguda",
  "Nagulamma Devi Temple",
  "Masjid E Alamgir Rh",
  "Ameerpet Mosque",
  "Masjid e Ashraf",
  "Shri Shri Shri Abhaya Sai Baba Temple Tirumala nagar  Almasguda",
  "Masjid-E-Bilal RA",
  "Masjid Sana Ayesha Ghani Ale hadees",
  "Jagannath Swami Mutt",
  "Abubakkar masjid",
  "Prasanna Anjaneya",
  "Vasavi Kanyaka Parameshwari Temple",
  "Hazrat- e- Abu Talib(AS)",
  "OLD EIDGAH",
  "Masjid E Dawood",
  "Sri Muthyalamma Temple",
  "Ujjayni mahakaali temple",
  "venkateshwara temple bkguda",
  "Raghu ram temple arch",
  "Hanuman Temple(Sri veeraanjaneya swamy temple)",
  "sri Bangaru Maisamma Temple",
  "Dargah begumpet",
  "hanuman temple",
  "Sri Venu Gopala swamy Temple",
  "MASJID-E-JAANI BEGUM",
  "Sri Sri Sri Muthyalamma Temple",
  "MASJID-E-QUBA",
  "Moosakhan Masjid",
  "Bheerappa Temple",
  "Survey no",
  "BERAPPA TEMPLE",
  "masjid jibraill sarwaree",
  "Sri Valli Devasena Sametha Kokki Naga Sumramanya Swamy Sannidhi",
  "Qutub Shahi Masjid ( Ahle sunnat wal jamat)",
  "Shivalayam temple",
  "KattaMaisamma Temple",
  "Sri Hari Hara Kshetra Ayyappa Swamy Devastanam",
  "Peddanana own temple",
  "Kandukur Hanuman Temple",
  "Sri Laxmi Sri Ganapati Sri Saraswati Devi Temple",
  "Hari Hara Kshetram",
  "Masjid e Fatima Naimatullah",
  "Sri Sanjeeva Anjaneya Swamy Temple",
  "Masjid-e-Ahmadi",
  "Varshasri Nandala",
  "Masjid E Abubakar Siddique rz",
  "Mamathaanil",
  "Masjid E Ahmed",
  "Bhavana",
  "Veerabadhra Swamy Temple",
  "Matha ka Mandir - Machleshwar",
  "Sona ka dukan",
  "Sri Shirdi Sai Baba Devasthanam",
  "Masjid Noor Mohammed Shareef",
  "Bheemarayuni Gudi",
  "Kakaguda Jadala Maisamma Temple",
  "MASJID E ABUBAKKAR",
  "Jamia Masjid Taleem Amlapur",
  "Apco colony bodrai",
  "Jama Masjid Quwwatul Islam",
  "Sangameshwara Temple",
  "Masjid-E-Akeel Shah",
  "Masjid e Ansaar",
  "Elikatta Shiva Maruti Temple",
  "Lord Shiva Statue",
  "sri maisamma temple",
  "Ramalingeshwara Swamy Devalayam",
  "Mohammedia masjid",
  "veeranjaneya Mandiram",
  "Muthyalamma Thalli TempleDundigal",
  "Masjid e Qutub Shahi",
  "Masjid e Abbasiya",
  "Sri Jagadamba Alayam",
  "Ashrafi Masjid",
  "MAHA RANAPRATHAP SHAKA GHMC PARK",
  "Jai Shree Abhayanjaneeya Swamy Temple",
  "Masjid Zahid Abbas",
  "Chilkuri Nalani Temple",
  "Jamia Masjid Al Azhar Ahle Hadees",
  "Shri hanuman mandir",
  "Al-Noor Masjid",
  "Venkateshwara and Saibaba temple",
  "SC Vinayaka Mandapam",
  "Masjid-E-Ahsan",
  "Sri Rama Alayam",
  "Sri Sri Sri Abhayanjaneya Temple",
  "Poleramma Temple",
  "Dattatreya Swamy Temple Kaallakal Telangana",
  "Masjid-e-Mustafa AC guards",
  "Seema Maggam Biotics",
  "Sri Nalla Pochamma Devalayam",
  "Lal Badshah Quadri Masjid",
  "Sri Rajasthani jangid brahman samaj",
  "Jai Santoshi mata mandir",
  "Durga Mata Temple",
  "Masjid Omer bin khattab(Tablig)",
  "MASJID-E-AZEEZULLAH",
  "Parvati Devi Temple",
  "Shivaalayam",
  "Naga devatha temple",
  "Masjid Mohamediya",
  "Dargha Hazrat Syed Shah Mohammed Zuhoor ul haq Hussaini Buqhari Quadria Chistia RA",
  "Satyanarayana Swami Temple",
  "Masjid-e-Jamal-e-Mohammadi",
  "Sri Krishna Temple",
  "Masjid-e-Mohiuddin",
  "DURGA TEMPLE",
  "Masjid -E- Quwwatul Islam",
  "Masjid-e-Osmania",
  "Sri Surya Narayan Temple",
  "Setharamanjaneya Swamy temple",
  "Chandrala Devi Temple",
  "Sree Chakra Lalithambika Jagadambika Temple",
  "Tulja Mata",
  "Rannaghar radha krishna math",
  "MASJID -E- AAZAMIYA NIZAMIYAH",
  "Masjid e Mohammadia Salafiya",
  "Mohammadia Masjid - Engine Bowli",
  "Shani Graha Temple",
  "SRI SANKAT MOCHAN HANUMAN MANDIRSAINAGR",
  "Masjid e Hazrat Ali",
  "Sri Maisamma Gudi",
  "Subramanyam Swamy Temple",
  "Masjid E Hashim",
  "Cheeni Masjid",
  "Chatrapati Shivaji Maharaj Park imliban",
  "Mahakali Temple East Kamaan",
  "Masjid-E-Tipu Khan",
  "Bharathmatha Temple",
  "MiM WATER PLANT Masjid E Banubi",
  "Sree Eadamma temple",
  "HANUMAN FRIENDS YOUTH ASSOCIATION",
  "SALANA URS-E-SHAREEF Masjid (Darga)",
  "Ravidas Temple Hyderabad",
  "Masjid Zorawar Khan",
  "SRI DURGA MATA TEMPLE",
  "Siva Temple",
  "Masjid e Mohammadia HHG",
  "Sri Matheshwari Muthyalamma Temple",
  "Masjid Fakerunisa Begum Saheba",
  "Shah Dastagir Baba Dargha",
  "Sri Padmavathi Goda Sametha Venkateshwara Swamy Temple",
  "Lord Bhulaxmi Temple",
  "Shree Kaal Bhairav Hanuman Mandir",
  "Dadmahal Maisamma Temple",
  "Masjid E Mama Badan",
  "Shiva Linga Temple",
  "NALLA POCHAMMA TEMPLE WEAKER SECTION",
  "Sarvatra",
  "Masjid E Samiya Aziz Fatima",
  "Mahabogh Bandar Basthi",
  "SRI SETHARAMA TEMPLE",
  "Masjid E Ek Khana",
  "Eid Gah Fox Sagar",
  "Masjid E RAHAMANIYA",
  "Sri Sri Sri Prasananjaneya Swamy Devalayamu",
  "Masjid-E-Mohammadia Markaz Nandanavanam Zone",
  "Dargah Syed Sha Fakruddin Sabri",
  "Lord RAMA Temple",
  "Thaggi Jail Masjid",
  "Masjid-e-Khalifa",
  "Sri Sai Baba Mandir",
  "matha mandir",
  "Masjid-E-Azizia",
  "Masjide hazrat Mohammed bandagi",
  "Jamia Mohmmadia Masjid",
  "Nagamma Temple karmika Nagar",
  "Sri prasanna venkateswara swami temple",
  "MD ASAD",
  "POCHAMMA BASTHI IBP",
  "Eidgah-E-Noorani",
  "Sri Indreshwara Swamy Devasthanam",
  "Pathan",
  "Sri Hanuman Mandir  Gollapally Station Thanda",
  "Sri Sri Sri Bangaru Maisamma Devalayam",
  "Sri Bhavani Naga Lingeswara Temple",
  "Girkamaisamma Temple",
  "Eid gah",
  "Masjid - e - Hazrat Bilal RZ",
  "Masjid - E - Azizia",
  "Jai babaa",
  "Vitthal Rukhmai Mandir Gachibowli",
  "Shivaji Chowk khanapur",
  "Masjid e Shah Mir Auliya (RA)",
  "Masjid E Julu Khana",
  "Kalabhairava Swamy Temple",
  "Sri Hanman temple",
  "Shri Samarth Kamdhenu Gowshala",
  "Sri Kali Mata Mandir",
  "Sri Veer Hanuman Temple",
  "Sufi Masjid",
  "o",
  "Dargha Hazrath Syed Abbas Shah Quadri Chisti Urf Peer Gaib Sahab (RH)",
  "Shri Kamakshi Ekambareshvarar Temple",
  "Hanuman Temple Kolanpaka",
  "Sri Abhya Anjaneya Swamy",
  "Bangarama Temple",
  "Masjid Mohammadia",
  "Boja thanda Hanuman temple",
  "Sri Sai Baba Temple",
  "Chinthalla pochamma temple",
  "Jannayya Guta Narasimhaswamy temple",
  "Pedamma Temple",
  "Hanuman Temple nayak nagar",
  "Sri Kota Maisamma Devalayam",
  "Sri Sitharama and Hanuman Temple",
  "NAGULAMA Temple",
  "Shree Muthyalamma Temple",
  "SRI VENKATESWARA THAPOVANAM",
  "Masjid e Abdul Razzaq",
  "Bho Laxmamma Devalayam",
  "Quddusia Masjid",
  "Jameya Masjeed",
  "Cheeryal temple chairman residency",
  "SRI SRI SRI REENUKA YELLAMMA THALI TEMPLE",
  "Sri Seetha Ramanjaneya Temple",
  "Yalamma Temple Dulapally",
  "Ameer Hamza Masjid",
  "Balaji Chandramowliswara Swamy Temple Brahmanwadi",
  "Masjid Darul ameen",
  "Ibadat Khana E Hussaini",
  "Sk panipuri  chat sentar",
  "Himayathnagar",
  "Kondal Raju",
  "Kotamissamia Temple",
  "Siddhi Vinayak Temple",
  "Dargha Hazrat Mehboob Subhani",
  "Masjid Shehnaz Amjad",
  "Masjid Abu Bakr Siddique",
  "Masjid E Mohammadiya Mumtaz Bagh",
  "Masjid-E-Karim",
  "Durgamma thalli temple",
  "Madina Masjid Bolligudam",
  "Masjid E Noor",
  "Jama Masjid Sardar bagh",
  "Bramarambica Temple",
  "Ghanpur jama masjid",
  "Sahib Ki Masjid Chelapura",
  "Goswamy Mutt",
  "Sri Bhoolakshmamma Devalayam",
  "Nisha",
  "Masjide maryam kammadanam",
  "Syedna Shah Sadullah Sahab Masjid",
  "Mallanna Swamy Temple",
  "balalayam",
  "Himayatul Islam Mosque",
  "Masjid-e-Shujat Khan",
  "Boddurai",
  "Sri Nallapochama Temple",
  "Jama Masjid E Paigah",
  "SRI KANAKA DURGA TEMPLE",
  "Annapurneshwari Mandir",
  "kummargadda pochamma temple",
  "Trishul Youth Association",
  "Mazjid -E- Fatima Begum",
  "Masjid-al-habib Ahle Sunnat Wal Jamaat",
  "Shri Visweswara Giri Kshetram",
  "Sri datta Sai Mandir C-",
  "Mosque  Karimguda",
  "Masjid e Amena",
  "Peddamma thalli temple",
  "Masjid-E-Zaki Shameem",
  "Darga E Hazrath Syed Shah Muhammed Hashim Hussaini Sahab Qilbla Rahamathulla Aleh",
  "Sri Ahobila Muth",
  "Sri Renuka Yellamma Temple",
  "Sri Yellamma Pochamma Devastanam  Balkampet",
  "Mosque Masjid",
  "Masjid-e-Yahiya",
  "Dr BR AMBEDKAR N BABU JAGJEEVAN RAM COMMUNITY HALL",
  "Dattatreya Colony Ganesh Temple",
  "Temple Tejaswinagar",
  "Dargah Sufi Hazrat Syed Ali Shah Meeran Quadri Buqari RH",
  "Toli Masjid",
  "Autonagar Masjid",
  "Masjid-E-Razzaq",
  "Masjid E Mohammedi",
  "MASJID E MOHAMMADIA IDA BOLLARAM",
  "Masjid-e-Yaseen",
  "Masjid E Ghousiya",
  "Sri Prasanna Anjaneya Swamy Devalayam (Upasana Gruha)",
  "Kowkoor Dargah",
  "Saibaba temple",
  "Hanumaan templecherabanda raju nagar",
  "Masjid-E-Hassan",
  "Scientific Colony Hanuman Temple",
  "Shree Hanuman Mandir",
  "Veerabrahmendra swamy Temple",
  "Mahankalamma TempleShivalayam",
  "Sri Anjaneya Swamy Devalayamu",
  "Qutub Shahi Masjid And EID GAH",
  "RAF MASJID",
  "Eak Minar",
  "Grave Yard",
  "Masjid Alia",
  "Arya Samaj Mandir",
  "Bhaktaanjaneya Swamy Temple",
  "Masjid e Hyderia",
  "Sri Gnana Venkateswara Swamy Temple",
  "Sri Karya Siddhi Hanuman Mandir",
  "Sri Bangaru Maisamma Devalayam",
  "Sri Sri Sri Virat Vishwakarma Temple Boduppal",
  "Hanumadeeshwara Sairam Mandiram",
  "Jama Masjid Mohammadia",
  "Masjid e Muhiyuss Sunnah",
  "Kaali Maata Temple",
  "Masjid E Sang",
  "Rajiv Gandhi phase",
  "Ganesh Mandapam IP colony phase",
  "Sri SeethaRamanjeneya Temple",
  "Sri Giri Sharada Kalyaana Venkateswara Swamy Devasthaanam",
  "Momin Choudary Masjid",
  "Masjid e Abu Bakr",
  "Ram Mandir",
  "Sri Maisamma Thalli Devalayam",
  "Sri Siva Sai Kshethram",
  "Madina Majid",
  "Sri Sri Pochamma Thalli Devalayamu",
  "MASJID E NOORANI MOHAMMEDIA",
  "Masjid - E -Mohammedia",
  "Harikrishna Sharma Purohith",
  "Masjid e RASHEED",
  "Pochammo temple RCI gate",
  "Madani Masjid Pahadi Shareef",
  "Jama Masjid Pahadi - Ahlesunnah",
  "Masjid e mahammadiya",
  "Sri thirukkan vaarahi matha",
  "Jama Masjid Medpally",
  "Teen Mandir",
  "MAHANKALI TEMPLE",
  "Upparguda",
  "Meraj Masjid",
  "Masjid-e-Rahmania",
  "Pochmma Temple",
  "Laxinarasimha temple",
  "Bodrai Korremula",
  "Sri Annamacharya Sametha Sri Swarasiddhi Venkateshwara Swamy Temple",
  "Lord Ganesha Shrine",
  "Eidgah Dargah e Shareef Hazrath Salar e Auliya (RH)",
  "Pasham Bai Maisamma Devalayam Mekaguda",
  "Hp dargah",
  "Latifi Masjid",
  "Mahaboobsubani Darga",
  "LAXHMI NARSIMHA SWAMY TEMPLE CHENNAPUR BALAJI NAGAR JAWAHAR NAGAR GRAMA PANCHAYATMEDCHAL DIST",
  "Mastan Baba Dargah",
  "Sri Abaya Anjaneya Swamy Temple",
  "Pochamma Devalayam Hari Nagar",
  "Shirdi Saibaba Temple",
  "Sri Sri Sri pochamma devalayam",
  "Ganesh Mandapam",
  "Masjid-E-Quba",
  "Sri Chintan Haran Ganesh Mandir",
  "Sri Nagraj Mandir",
  "Ismail Chowdri Masjid",
  "Navagralu",
  "Yogeswara Temple",
  "Masjid E Noor ()",
  "Mosquesalamfarsi",
  "Wakf Land ( Muslim Community )",
  "MASJID-E-ABBAS GULSHAN",
  "Nalla pochamma and Mahankali amma temples",
  "Renuka Yellamma Temple Thativanam Bachannapet",
  "Vinayakudi mandapam",
  "Samakka Sarakka Temple",
  "Devi Temple",
  "MASJID-E-NOOR",
  "Veerabhadra swamy temple veerannagudem",
  "Shri Sankata Mochan Hanuman Temple",
  "Majid-E-Bilal",
  "KJR Complex",
  "Katta Maisamma Temple Sree Homes Colony",
  "Sri Godha Devi and Padhmavathi sametha Venkateswara swami devalayam",
  "Masjid E Umme Salma (Ahle Hadees)",
  "Masjid-E-Syed Wali",
  "Masjid e gause o khwaja",
  "Darul Uloom Masjid",
  "Sri Shirdi Sai Baba Samajam",
  "Narayan Maharaj Mutt",
  "MASJIDE KALAAN Jamia Nizamia Road",
  "Mahboob Shahi Masjid",
  "Masjid-E- Hazrath Mirza Sardar Baig",
  "Muthu maariyamma devalayam hydernagar",
  "Sri Vijayaganapthi Bhavani Shankara Abhaya Anjanaya Swami Devalayam",
  "Sri Nalla Pochamma Ammawari Alayam",
  "Bhadra",
  "Saibaba Mandir Isnapur",
  "Masjid E Nabavi",
  "Masjid e Akbar Aahle Sunnath Wal Jamaat  Ambedkar Nagar Gajulramam",
  "Masjid-E-Sayeed",
  "Sri Lakshmi Narasimha Swamy Devalayam",
  "Lov Kush Mandir",
  "JAMAT E ISLAMI HIND JUBILEE HILLS OFFICE",
  "MasjideIlaahi",
  "Masjid E Chamkura",
  "Masjid Sajida Begum",
  "Sri Datta Hanuman Temple Harikrishna Sharma",
  "Masjid E Mahmood",
  "Sri Pochama Temple",
  "Osmania Masjid",
  "Anantha Padmanabha Swamy Temple",
  "Jagadamba Sevalal Temple Devula Thanda",
  "Masjid E Osmania",
  "Lodh Kshatriya Samaj ka Pahad",
  "Masjid e kouser",
  "Mahaboob subhani dargah burg",
  "Merrammayadi sevalal maharaj temple",
  "Old Hanuman temple",
  "Kolombai Maisamma Temple",
  "Masjid E Meraj",
  "Masjid e Tawheed - Ahle Hadees",
  "SriKrishna Temple",
  "Afzalgunj Jamia Masjid",
  "Markandeya temple",
  "Masjid bengali begum",
  "Sitla Mata Temple",
  "Masjid-E-Karimiya Masjid",
  "Ali Masjid",
  "Masjid E Noorul Islam",
  "Mutyalamma Temple Khajaguda",
  "MATA Temple",
  "Sri Vasuki Subramanya Nava Nagendra Devalayam",
  "Kota Maisamma Temple  Youth Members",
  "Masjid-E-Al Sahaba RA",
  "Sri Gandimaisamma Alayam  Kumhar Basti Nanakramguda",
  "Shiva alayam mahadevapuram",
  "Masjid-e-ilahi naqshebandia  Bargah e hazrat syed Yahiya Pasha Naqshbandi (ra)palamroadbahadurpura",
  "Dilkushnagar Mosque ahelesunat ul jamat",
  "Devatalagutta Ganga Temple",
  "Sri Vijaya Ganapathi Temple",
  "Old maisamma temple",
  "Masjid-e-Alamgir",
  "Sri Narmadha Omkareshwara Swamy",
  "Eedamma Temple",
  "Masjid E Khaled Bin Wali",
  "Jamia Masjid Nandigam SA Bhai",
  "Sri HANUMAN TEMPLE KALLAKAL",
  "Varaha swamy yagashala",
  "Sri Ramchanderji Temple",
  "Satgudi Temple(Seven Temple)",
  "Sri Padmavati Venkateshwara Swamy Devalayam",
  "MASJID-E-KAVELI",
  "SRI SRIDEVI BHUDEVI SAMETHI SRI VENKATESHWARA SWAMY  SRI ABAYA ANJANEY SWAMY",
  "Daftar e majlis e ulama e hind",
  "Madina masjid",
  "Sri uma maheswara devalayam",
  "Jama Masjid Mohiuddin",
  "Majid E Quadria",
  "Sri Marramma Alayam",
  "Sree Veera Venkata Satyanarayana Swamy Devasthanam",
  "Pochamma Templu",
  "Quba Masjid",
  "Masjid e nabi",
  "Masjid E ahmedguda",
  "CHAMINAR",
  "Baba Govinddas Math",
  "Sri Vaishno Mata Mandir",
  "Kanyaka Parameshwari Temple",
  "Masjid E Ali Ahle Hadees",
  "Masjid e Hibatul Jabbar",
  "Sri Kalki Bhaghavan Temple",
  "Hz Syed Asadullah RH",
  "sri panchamuka santhana nagadevatha temple",
  "Masjid E Fazle Siddiqi",
  "Konda Swamy Ganesh Centre",
  "Masjid GhatPally",
  "MASJID-E-IQBAL",
  "Hanuman  Seetha Ram Temple Lingampally",
  "Musjid Mosque",
  "Phool Hanuman Temple",
  "Sharfia Masjid",
  "Aadilakshmi Alivelumanga sametha sri Venkateshwara swami(Balaji) Temple",
  "Veeranjaneya Shiva Panchayatana Temple",
  "Hameedunnisa Ka Dargah",
  "Hanuman Youth Association",
  "Shambu Lingeshwara Swami Temple",
  "Masjid-E-Ilahi",
  "Masjid Balanagar",
  "Vadera bastty maisama",
  "Mahadevji Temple",
  "Masjid-e-Quba",
  "Hanuman Templekadiyalakunta",
  "Nandishwara Temple",
  "Vinayaka Mandapam",
  "Sara e Mir Alam",
  "Madeena Masjid",
  "Nalagond",
  "Venugopala Swamy Temple",
  "Sri Sri Pochamma Devalayam  Dr B R Ambedkar Yuvajana Sangam",
  "Masjid-e-Aleem",
  "Pochamma basthi",
  "Shri Hanuman Temple",
  "Beerappa swami alayam M M Kunta",
  "Kaal Bhairav Hanuman Mandir",
  "Durga Matha Golden Temple",
  "MASJID-E-GUND-O- SHAAH",
  "Masjid Abdullah Bin Ibrahim - Islamic Mosque  Education Centre",
  "Ghana Saraswati Ammavari devalayam",
  "Sravan Kumar Sharma",
  "Guduru Renuka Ellamma Temple",
  "Renuka Yellamma Temple",
  "Bhavani Shankara Devalayam",
  "Sri Gananadha Youth Group",
  "Sri Bhadradri Seeta Ramachandra Swamy Temple",
  "Madarsa Arabia Kousaria",
  "Rikab Jung Masjid",
  "Matha Temple",
  "Santoshi Mata Temple",
  "Masjid e Mohammed Bandagi",
  "Kanaka Durga Mata temple",
  "Masjid e Shakker",
  "Kamakshi Sametha Ekamber Nath Devalayam",
  "Sri chithaarama",
  "Masjid E Ibrahim",
  "Masjid-e Niyazuddin Julkal",
  "Suthariguda pochamma temple",
  "Masjid-e-Gareeb Nawaz",
  "Sri Dattha Sai Devalayam",
  "Sri Renuka Yellamma Nagalakshmi Devalayam",
  "SRI SADATTE RENUKA ELLAMMA",
  "SHIVA BAKTHAMARKENDRYA DEVALAYAM",
  "Jama Masjid E Mohammadia",
  "Sri Sri Renuka Yellamma Devalayam",
  "Masjid -e- General Bazaar",
  "Kailasam Gutta",
  "Mosque And Madarsa",
  "Qutub Shahi MASJID",
  "Maniyar Patti Masjid",
  "POCHAAMA TEMPLE",
  "Pandurang Temple",
  "Yellamma Thalli Temple",
  "Kavitha Fabricators",
  "Darul Uloom ibrahimia",
  "NAG",
  "Sri ram temple",
  "Madarsa Playground",
  "Masjid Aqsa",
  "Durgamata Temple",
  "Gausiya Masjid",
  "Masjid Bin Baaz",
  "Nagareswara swamy temple chilkoor",
  "Eidgah Entrance Arch",
  "Naga Devatha Putta",
  "Ayyappa Swami Temple",
  "MASJID-E-OMER",
  "Sai Baba and Ammavari Temples",
  "Baba Darga",
  "Masjid E Quba Alwal",
  "MASJID-E-HASHMIA",
  "Masjid E Yaseen",
  "Masjid E Taikhana",
  "Masjid e siddiquia Namaz Timings",
  "Anjaneya Swami Temple",
  "Abhaya Anjaneya Swamy",
  "Sri Neelkantheshwar Mahalakshmi Mandir Laldera",
  "Sri Bhagya Laxmi Mandir Chatri Begum Bazaar",
  "Virat Hanuman Mandir",
  "Parameshwara Ramalayam",
  "Pujari Jharni Narsimha Cave Temple",
  "Kumawat Samaj",
  "Masjid e bilal",
  "Shiva  Narasimha Swamy Temple",
  "Swathi jyothishalayam",
  "Sita Rama Mandir",
  "Sri Nalla Pochamma Ammawari Devasthanam",
  "Kancharlaguda Hanuman mandhiram",
  "MASJID-E-AQSA",
  "Kashibugga",
  "Eidgah KOLANUPAKA",
  "Sri Abhaya Anjaneya Swamy DevalayamRamnagar",
  "Hanuman Khamman Sadar Bazar",
  "Masjid e Fateh Maidan",
  "Godasu Anthaiah Mudiraj Ananth",
  "Narketpalle",
  "Sri Sri Sri Peddamma Thalli Devalayam",
  "Masjid-e-Noorani",
  "Masjid-e-Khaja Moinuddin Shareef",
  "Hill Street Dargha",
  "Masjid e Ahle Hadees",
  "MASJID E HAZRATH ABBUBAKAR SIDDIQ RAZIALLAHUANHU",
  "POCHAMMA THALI TEMPLE",
  "Temple Durga",
  "Sri Shrdi Saibaba Mandiram",
  "JAMA MASJID E NOORI",
  "Masjid-e-khasim",
  "Tuljabhavani Temple",
  "Masjid e Gafooria",
  "Shree Kethaki Sangameshwara Temple JharaSangam",
  "Turkapalli Masjid",
  "Kanaka Durgamma Temple",
  "Pochamma Temple Sc",
  "Sri sitharamanjaneya swami dhevalayam",
  "Masjid E Umer Farooq",
  "Mallikarjuna Swamy Temple(Shivalayam) And Goshala",
  "Sri Sri Sri Ramalingeswara swami temple",
  "lord Hanuman Temple",
  "BILAL MASJID TALAB KATTA",
  "The Urban Temple",
  "Dharga",
  "Masjid Kallakal",
  "Kushaiguda Ganesh",
  "Masjid E Niloufer (Paltan Ki Masjid)",
  "Pedhamma Temple",
  "Dargah Shareef Hazrat Syed Ameer Alishah Urf Nakte Shah Baba",
  "Saibaba Temple Balajinagar Mailardevpally",
  "Masjid Noorulasfiya",
  "Panchamukhi Hanuman Temple",
  "Jayaguru Thakur Nigamananda Asan Mandir",
  "Sri Kanaka Durga Devi Temple",
  "Lord Sri Abhaya Anjaneya Swamy Temple",
  "Masjid - e - Zainul Abedeen",
  "gandigudem malikarjuna swamy temple",
  "Khaja Gareeb Nawaz Dargah",
  "Mahatma Nagar hashmathpeth X road",
  "Rebels youth association",
  "Dargah (Aastana-E-Shamsia)",
  "Ankushapur Masjid-e-omarfaruk",
  "Gandi maisamma temple",
  "Owasi masjid",
  "Mithilanagar Ramalayam",
  "Jnanashram",
  "Sri Shirdi Sai Baba Mandir",
  "Blue star friends association",
  "Karkhana Idgha Qadeem Eidgha",
  "TULJA BHAVANI TEMPLE",
  "HINDU TEMPLE Historical structure",
  "ISKCON Hyderabad",
  "Hanuman Temple (Hanuman Mandir Kowkoor)",
  "Shri Shirdi Sai Temple",
  "Masjid-e-Ujale Shah Sahab",
  "Sri Mahankali Pochamma temple",
  "Sri Sai Vishwanatha Kshethram",
  "Mahuboo Darga",
  "Samayapuram Maaremma Temple",
  "Sri Shiva Rama Hanuman Temple",
  "Hafizpet VAIKUNTA DHAMAM",
  "Masjid E Noor - Deoband",
  "Shree sachiyay Mata Mandir",
  "Masjid- E- Gulam- E- Murtuza",
  "Masjid-e-Rahmania Ahle Hadees",
  "Masjid e kadriya chintalkunta check post",
  "dargah hazrat Jafar sarwaree",
  "Sattemma Swamy Yellama",
  "Boranchamma Temple",
  "Masjid-e-Kausar",
  "Jeth Puri Nagamaisamma Temple",
  "Mallanna temple",
  "JAI DURGA Bhavani Youth Association",
  "SBH COLONY MASJID",
  "Osmaniya masjid",
  "Jama Masjid Devdhi Nawab Dulhe Khan",
  "Masjid-e-saara",
  "Raja Gopuram",
  "Masjid Madina e Munawwara Madina",
  "Ghatkesar Jama Masjid AhleSunnat wal Jamat",
  "Saleema khatoon Masjid",
  "Mari Amma Temple",
  "Vinayaka Swamy mandiram",
  "Masjid e Aliya",
  "BAPUNAGAR MASJID",
  "Masjid-A-Omer Farooq",
  "Sri Venkateswara Swamy temple",
  "Gundam beeramguda",
  "Masjid Noor E Muhammadi",
  "Durga",
  "Lotus Temple",
  "Hanuman Old Temple",
  "ASHOOR KHANA E SHAHZADE QASIM (A S)",
  "Peddamma Talli Temple",
  "Masjid E Mohammadia Vinayak Nagar Neredmet",
  "Ashoorkhana e Moula Ali Dargah",
  "Dundigal Shivalayam",
  "Viswakarma Temple",
  "Sree Sita Ramanjaneya Swamy Devalayam",
  "JAME MASJID E IHYA-US-SUNNAH",
  "Tripura sundari temple",
  "MASJID GPRA children park",
  "Sri Gali Pochamma Devalayam  Kistaipally",
  "Sri Radha Krishna Temple Kumawat Samaj",
  "gandigudem point",
  "Sri Sankata Mochan Hanuman Temple",
  "Ghouse- E- Azam Dastagir Chilla Dharga",
  "Jama Masjid-E-Hussaini",
  "Shri Shri Shri Vanadurga Mata Temple",
  "Mohammadia Masjid Kompally",
  "Chowlpally West Jamia Masjid",
  "Sri maisamma temple",
  "Sai Baba Temple Kolanupaaka",
  "Mahankaali Temple",
  "Masjid-E-Ahmed",
  "Masjid e Mukarram Shaheed",
  "Venkata Vamsi Temple",
  "Sri Mallanna Alayam",
  "Masjid E Umar Bin Khattab rz Ahle Hadees",
  "Vinayaka Mandapam Sri Jadala Rama Lingeswara Swamy Devalayam",
  "Sri Raktha Maisamma Devalayam",
  "Eidgaah",
  "Hosamna Mandir",
  "Banti",
  "Singer Sitaram marindi",
  "Sri Renuka Yellamma Patnala Mandapam",
  "Sri Yellamma Pochamma Temple Mokila  Shankarpally Road Hyderabad",
  "Shiridi Sai Seva Ashramam  Feet Saibaba",
  "Maqdumpally Mutt",
  "Sri Neelakanteshwara RamachandraAnjaneya DarmaSai Temple",
  "C R Nagar Hanuman Temple Kothwal Guda Shamshabad",
  "Swar Mandir",
  "Alpha function hall",
  "Srinivasa bhakti prachara peetam",
  "Sunny Saketh Palley",
  "Ayya devudu",
  "Masjid Kothapet",
  "Yellama talli",
  "Madhukar Darga",
  "Masjid E Bowli",
  "Sri Gandi Maisamma Devalayam",
  "Masjid e Noor",
  "Narsapur Chowrasta Lord Shiva Temple",
  "Masjid-e-HAL",
  "Mohemdia Masjid",
  "Safil Maisamma Temple",
  "Sri Katta Maisamma Temple",
  "Masjid-e-Jani Begum",
  "maisamma temple",
  "Sri Shirdi Sai Baba Devalayam",
  "Anjaneya swamy temple yenkeypalli",
  "Shri Pochamma Temple",
  "Sree Shiridi Sai Baba Mandir",
  "Masjid E Mamoor Dargha",
  "Asurkhana gollabasti",
  "SYED SHAH SHOHRABUDDIN HUSSAINI OULIYA (RA)",
  "Dairy Farm",
  "Old Mallikarjuna Swamy Temple",
  "Masjid-e-Ibhrahim Khaleel",
  "Sri Kethashwaram Mahendra Temple",
  "Jonnada pochamma temple",
  "Hanuman Statue Diamond Heights",
  "Bommala Gudi",
  "Kalimandir",
  "Yenikepally Maisamma Temple",
  "Masjid-e-Osman-e-Ghani",
  "SREE VIJAYA GANAPATHI TEMPLE  Vinayaka nagar colony",
  "Anjaneyaswamy Temple",
  "Masjid E Almas",
  "Masjid-E-Rasool-E-Akram",
  "AMINA Masjid",
  "Masjid-e-Quboor",
  "Ayyapa Swamy Hanuman Temple",
  "Lord Saibaba Temple",
  "Shri Krishna Mandir",
  "Masjid-e-Imam Ahmed Raza",
  "kanakadurga Temple",
  "Yellamma Pochamma Sheetla Mata Temple",
  "Jama Masjid (Safa Masjid)",
  "Subhramanya Swamy Temple",
  "SREE MUKKA MAISSAMMA TEMPLE",
  "Masjid-e-Afzal Khan",
  "Pochama temple",
  "Reddy Sangam Vinayaka Mandapam",
  "Sri Seetha Rama Laxmana Sametha Anjaneya Temple",
  "Yadadri Paadhala Mandapam Rajagopuram",
  "Kotamaisamma Temple",
  "Lodh samaj pahad",
  "Masjid-E-Mohiuddin",
  "Shashank",
  "MASJID-E- Mohammadiya",
  "Mahankali temple gundlapochampally",
  "Nalla Pochammatalli Temple",
  "Sree sree Darbaar matha association",
  "Venkateshwara Swami Temple",
  "Chinna mallappa Gutta",
  "Masjid Chilla Nasir Jung",
  "Jamia Masjid Siddiambar Bazar",
  "masjid e Ahmediyya",
  "masjid e fathe maidan",
  "Chinthala maisamma",
  "Sri Shiva Subramanya Swamy temple",
  "Srikamakshi srividya peetham",
  "Jai Shree Hanuman",
  "Renuka Ellama Temple",
  "Masjid e Miya Khan Sahab",
  "Masjid e ghausia",
  "Ali Peer Masjid",
  "Sri Yellamma Thalli Temple",
  "Sangameshwara Temple Front side",
  "Maariamman Temple",
  "Bavani Temple",
  "Soudamma Temple Madharam",
  "Masjid e Abubakar",
  "BEERAPPA SWAMY TEMPLE",
  "Masjid e Mohammedia",
  "arike vari maisamma temple",
  "Eidgah Power",
  "Dargah Hazrat Syed Ahmed Shah Quadri RA",
  "Sri Sri Nallapochamma Temple",
  "Sree Prasanna Anjaneya Swamy Temple",
  "Sri alimelumanga sarvayya vedapathasala",
  "Masjid E Ilahi",
  "Masjid Maruthi Veedhi",
  "SHRI VENKATESHWARA SWAMI TEMPLE",
  "Urdu school",
  "Kota Maisamma Temple Pathabasthi",
  "MASJIDE-NABI (SAALIHEEN MASJID)",
  "sarva siddhi vinayaka Association",
  "Sri Sai Baba Devalayam",
  "Ganesh Pandal",
  "Masjid Fatimah",
  "Sri nalla pochamma gudi washnig side Secunderabad",
  "Uppalaamma Temple lane",
  "Jamia Masjid Gate",
  "Masjid E Abu Bakar",
  "Rathifile Mosque",
  "Sree Venkateswara Temple House",
  "Masjid e zubeda",
  "MASJID-E-HAJIRA",
  "shivaalayam Temple",
  "Maheboob Masjid e Ali",
  "Yellamma And Durgamma Temple",
  "Snake Hill - Putta",
  "Maisamma Teample",
  "Sri Bhaktha Anjaneya Swamy Temple Ankushapur",
  "Ayyappan Temple",
  "Ayyappa temple kerala style",
  "Masjid E Jamatul Muslimeen",
  "Mnjo",
  "MASJID",
  "Sri Kamakshi Sri Vidya Peetam",
  "Temple Kalyana Mandapam",
  "Masjid E Salman Farsi (Ahle Sunnat Al Jamat)",
  "Sri Mythti Welfare Association Vinayaka Shes",
  "Maisammaguda Temple",
  "Hanuman Mandir IDA Bollaram",
  "Masjid In Bomankunta Azeem villa",
  "Masjid E Aziziya",
  "Pochamma Gudi Budvel",
  "Masjid-e-Gada Baig",
  "Maisamma Pochamma Temple",
  "Seven Temples",
  "Sai Baba Temple Machabolarum Select Talkies",
  "Sri Renuka yellama Temple",
  "Sri Satya Sai Heavees",
  "MASJID-E-NOOR (CHENNA REDDY NAGAR)",
  "Sri Sri Sri Nampally Baba Samadhi Mandiram",
  "Maktha Mosque",
  "Masjid-e-Mustafa Yaar Khan",
  "Sri Rama Chandra Swamy Temple",
  "Sri naga devatha renuka yellama durgamma temple osmania university",
  "Shri Renuka Yellamma Temple",
  "Narasimha swamy temple",
  "Mata Mandir",
  "VANAR SENAGOLDEN FRIENDS CLUB",
  "Mahalaxmi Temple",
  "Masjid E Dost Ullah Baig",
  "Jama Masjid Jumerat bazar",
  "Pandu",
  "ABHI",
  "Deva Sri Ganesha association",
  "Godasu Anthaiah Mudiraj",
  "Masjid-e-mohammadia",
  "Sri Sri Sri Durga Devi Mallikarjuna Swamy devasthanam",
  "Sri Bhoolaxmi Temple",
  "Tulja Bhavani temple",
  "Eidgah-E-Bilal",
  "Makbara of SYED WAZIR ALI ZAHEER WAJU",
  "Vishwa Sai Baba Mandiram",
  "MOHAMMEDIA MASJID AHLE SUNNAT UL JAMAAT",
  "Masjid-e-Qutub Shahi",
  "MiskeenShah Masjid",
  "Bangaru Mutyalamma Temple",
  "BAL MANOHAR YOUTH ASSOCIATION",
  "KVedanth",
  "Masjid-e-Anas",
  "Hanuman Temple Autonagar",
  "Balaji nagar hanuman temple",
  "Masjid e Muhammad Azimul deen",
  "epublishing",
  "Pochamma Temple Savlaram",
  "Fintech services mosquito Mesh and blinds",
  "Sai baba temple",
  "Sri Laxmi Sarees",
  "Parvati Mata Temple",
  "Lords Mosque",
  "Jama Masjid Qutub Shahi",
  "Bhaktha Anjaneya Swamy temple",
  "maisamma temple singareni colony",
  "Friends youth association",
  "Alekvi Masjid Ground",
  "Masjide-E-Ali",
  "Masjid E Mohamadia",
  "Nagulamma Temple",
  "Hanumann temple",
  "Jamia Masjid Mohammadia",
  "Masjid E Muhammadia",
  "Jai yuva shakthi youth club Rajesh Nagar colony Chengicherla",
  "Sri Bhavani Mata Mandir",
  "Ashurkhana Al Husain AS",
  "Jama Masjid E Almas",
  "Markandeya Temple",
  "Masjid E Ammar",
  "Home",
  "Masjid In Indra Karan",
  "Sri Laxmi Narasihma Temple",
  "Masjid-e-Ek Khana",
  "Jammi chettu",
  "Dharma vidya Devalayam",
  "Sri Laxmi Narasimha Youth Club",
  "Mustafa MasjidKorremula",
  "Ganesha shrine",
  "Sree Durga Devi  Vinyaka Usatv MandapamRangapur",
  "Bangaaru Maisamma Devalayam Mekaguda",
  "Sri Sri Sri Anthagiri Maisamma Devalayam",
  "Masjid E Koya",
  "TEMPLE KOLAN FARM S",
  "Kali Matha Temple",
  "Sri Sant Sevalal Maharaj and Sri Durga Bhavani Mandir  Velimela Thanda",
  "Sri Rama Temple",
  "Katta Maisamma",
  "Masjid-e- Mohammedia",
  "Polerama Temple",
  "Sri Varala Mallana Temple",
  "KARYA SIDDHI VINAYAKA SWAMY temple",
  "Mahankali",
  "MASJID E AKTHAR GULSHAN",
  "Masjid e Quba Phool Bagh",
  "Hanuman Temple And shivalayam",
  "BEERAPA TEMPLE NEW",
  "Ganesh mandir Group center CRPF",
  "Shreee Durga Bhavani Maata Temple",
  "RAHMANIYA MASJID",
  "Masjid e khan Mohammad khan",
  "Sri Mahan Kali Temple",
  "Chandra Mouliswara Swamy Temple",
  "Bangaru Maisamma temple",
  "Jetpuri Maisamma Devasthanam",
  "Masjid E Shah E Alam Mahboob E Alam",
  "Masjid Syed Shah Asadullah Hussaini",
  "Murali Manohar Temple",
  "Jamia Masjid E Arsh mahal",
  "Shaikh Mahboob Masjid",
  "CMR Technical Campus ( Block - C)",
  "Masjid-E-Faqrul Islam",
  "Pochamma Temple Arch",
  "Sri Vitthal Rukhmani Mandir",
  "HINDU TEMPLE Gudi",
  "Darga Hazrath Syed Sadath",
  "Rajanna Temple Khanapur",
  "Geetha Gnyana Mandiram",
  "Masjid-e-Lutfullah",
  "MASJID E MIR MEHBOOB ALI KHAN",
  "Masjid Saherwardia",
  "Sri Gajjala Papamma Temple",
  "Madarasa Islamia Zia Ul Quran",
  "Masjid Sarah Shahidah Rahmat",
  "Sri AmmaBhagavan Madinaguda Temple",
  "Masjid e Rahman",
  "Shiva Mandir",
  "Masjid-E-Aukhad",
  "Padmaakshi Temple",
  "Swami Vivekananda Statue",
  "Sri Sri Pochamma Temple",
  "sri pochamma temple",
  "JAMA MASJID MOHAMMADIYA",
  "Masjid-E-Jama Peerlaguda",
  "Small shrine",
  "Ammavari Temple",
  "Gangi Renu Chettu Temple",
  "Sri Veerabadra Swamy Devalayam  Kondakal",
  "renuka yellamma temple",
  "Masjid also",
  "Shree Laxmi Venkateshwara Swamy Temple",
  "Sree Prasannanjaneya Swami Devastanam",
  "opp Malayalaswami Matt",
  "MASJID E ZAHEDA",
  "HIE Masjid",
  "Maisigandi  Keshampet",
  "EC Nagar - Bangaru Yellama Talli Temple",
  "Radha pakala",
  "Masjid e Mehmoodunnisa",
  "Sri Sri Tattva",
  "Gandhi stach chennaram",
  "MATHA TEMPLE",
  "NAMAZ HALL",
  "MASJID KESHWARI BEGUM",
  "Masjid-A-Amna-Jamal",
  "Sri Vishwaksena Swamy Aalayam",
  "Masjid E Momin",
  "Sri Renuka Yellamma Maisamma Temple",
  "Masjid E Mumtaz Mehdipatnam Pillar No",
  "Syed nagar",
  "Chilla Mubarak Hzrt Qutubul Madar urf Zinda Shah Madar Rht",
  "Markaz e Khidmath e Khalq",
  "Noorul Umra Masjid",
  "Nadergul",
  "Nagulamma Gudi",
  "beerappa temple",
  "Sri Santoshi Mata Temple",
  "Masjide Hussaini Information Colony Hayathnagar",
  "Geetha darshanam",
  "Temple of Goddess Durga",
  "Masjid E Ibrahim Ahle Hadees",
  "Bela Colony Temple",
  "Hanuman Temple Mallapur",
  "Saireddy guda",
  "Apco Colanay Boddurai",
  "Khairatabad Qutub Shahi mosque",
  "Masjid Irum",
  "Devi Ma Temple",
  "Sant Sevalal and Jagadamba Temple",
  "Renuka Yellamma Putta",
  "Crystal Town Masjid-e-Abdul Haleem",
  "Masjeed e rasheediya",
  "Masjid E Syed Abdul Razzaq",
  "Masjid e Fathima",
  "PplTemple stars",
  "Temple Rose Real Estate Private Limited",
  "Shirdi Sai Anna Prasaada Shaala",
  "Masjid e Qaisari",
  "Addamma Temple",
  "Shri Pochama Temple",
  "Shri Pochama Devalayam",
  "Duraga mata temple Ambedkar Nagar",
  "Durga mata temple",
  "Masjid-e-muhammad musabbeh alwahshi",
  "Masjid-E-Siratal Mustaqeem (Ahle Hadees)",
  "Sri Renuka yellama  Kali Mata  Sai Baba temple",
  "Jayanth Darga",
  "Masjid e sabeel",
  "Dargah Shareef",
  "Nalla alochana temple maheswaram",
  "Sri Sanjeeva Anjaneya Swami Devalayam",
  "Shri Maisamma Temple",
  "Edhamma talli dhevalayam  Rajaka sangam",
  "Masjid-e-Mohammed Hussain",
  "Parashuramula Devalayam",
  "Somalingeshwara swami Temple",
  "POCHAMA THALI TEMPLE",
  "sri komaravelli mallikarjuna swamy temple",
  "Masjid-e-Alamgeer Sun City",
  "Shivalayam Great Bath",
  "Sri Sri Sri Yellamma Pochamma Temple",
  "Arjun Ravidas",
  "masjid e moin",
  "Stambala Maissamma Temple",
  "Sri Venkateswara Veeranjaya Swamy Temple",
  "Arqam Masjid",
  "Masjid-E-Ghousia",
  "Masjid E Firdous (Ahle hadees)",
  "Ganesh Mandapam Mallikarjuna Youth",
  "Masjed raigir station",
  "chittaramma temple",
  "Khaseem Baba Dargah",
  "Hanuman Temple Mspl",
  "Masjid E Ilahiya",
  "Dargah Ghause E Paak Masjid",
  "Bal Reddy Nagar Ganesh Temple",
  "Sri Eedamma Temple",
  "Masjid - E - Umar Farooq",
  "Ganesha temple",
  "Neelesh street",
  "Masjide Bilal",
  "Sree Durga Bhavani Temple",
  "Masjid- E- Syedna Umer Farooq",
  "Masjid-E-Shukur",
  "Masjid Mohammedi Begum",
  "Masjid E Ghazi Miya",
  "Farah Masjid",
  "Masjid E Khaleeq",
  "Shiva parvathi youth ganesh",
  "Husainia Hazrath Imam Al Qaim (as)",
  "Dargah Hazrath Salar e Auliya (RH)",
  "Chatrapathi shivaji Maharaj Chowk",
  "Sri Rama Mandir",
  "Sri Mahadev Mandir",
  "MATTHAM BAAVI(hanumanula GUDITemple)",
  "Hanuman TempleKondakal",
  "Arthagiri Shathram Malella Gattu Sri Venkateshwara Temple",
  "Saraswathi Temple",
  "Eid Ga",
  "Shivalayam KorremulaLord Shiva Temple",
  "Pochamma Yellamma Temple",
  "Sri bhramaramba kethamma Mallikarjuna Swamy",
  "Hanuman Temple Modharlaguda",
  "Perumal Venkateshwara Swamy Temple",
  "SREE VENKATESHWARA SWAMY TEMPLE",
  "Mallanna Swami Temple",
  "Heramba Ganapathi Devalayam",
  "Four Temple",
  "Abu-Bakar Masjid",
  "MASJID E HAFEEZA SHAEEN",
  "Astana e yousufiya pili dargha",
  "Ramalaya Mandir",
  "Sree Hima Durga Kanaka Durga Devi Temple",
  "Masjid-E-Syedna Ameer Hamza",
  "SLV Temple",
  "Gundam",
  "Kaveli Ki Masjid",
  "AMMAVARI GUDI",
  "Hanuman shrine",
  "SHIVALAYAM TEMPLE",
  "Sri Pochamma tempul",
  "Masjid-E-Hajira Ahle-Hadees",
  "Venugopal Swamy TempLe",
  "Mucherla Mosque- Abdul Ghani",
  "Badam Masjid",
  "MAISAMMA TEMPLE",
  "Nalla pochamma temple",
  "Mata Temple",
  "Gayatri Bhavan",
  "Masjid-e-Babri Alawa",
  "Aastana E Mahboob E Chaman Barga E Quadriya",
  "Masjid e mehraj",
  "Madarsa Darul uloom gyara shuhada",
  "RAHMANI TAILOR",
  "Jama Masjid Tondpally",
  "Pushkarini Sri Anjaneya Swamy Temple",
  "Chittharamma temple",
  "Santhapur Bodrai",
  "BODDURAI UPPALA MAISAMMA TEMPLE",
  "Masjid e khateeja tul kubra RH",
  "Masjid Syed Murtuza Ali",
  "Brothers Youth Association Kushaiguda",
  "MSAJID-E-ZAKARIYAH-ALEH-SALAAM(Swaleheen Masjid)",
  "Khanqa e yaqoobia nooria lb nagar",
  "Sri Bhavani Rama Lingeshwara Alayam",
  "Ratnalaya Majeedpur Tg",
  "Khidki kai mahaveer mandir",
  "Azampura Anand Nagar Harijan Basthi",
  "Sri mahaganapathi panchayathana devsthanam",
  "masjid-e-syedamiyanew road chanchalguda",
  "Sri Shivaganga Raja Rajeshwara Swamy Devastanam Maheshwaram",
  "Masjid-e-Saleha",
  "NooraniMosque",
  "Om Janda",
  "Bhavanamma Temple",
  "Mata wale Urmila bai",
  "Shiv Mandir",
  "Kota Maisamma Devalayam",
  "Sri Suryagiri Yellamma Devastaanam",
  "SHWETHA LINGESHWARAALAYAM",
  "Nalla Pochamma Temple Pochamma Basthi",
  "Masjid E Saleema Khatoon",
  "Kuruma sangam",
  "Shri Krishna Gau Shala",
  "SATNARYANA TEMPLE",
  "Shiva Alayam",
  "Shaiva peetham kavadiguda",
  "AMBEDKAR NAGAR",
  "ZAKI UDDIN MAGGAM WORK",
  "Bhangarimaisamma temple",
  "ASHOOR KHANA E HAZRAT QASIM",
  "Venkateswara",
  "AL Noor Masjid",
  "puligutta AMMAVARIi temple",
  "Swamy Dhakshina Dwaramu",
  "Namaz Hall",
  "Masjid e Mola khan Qadari",
  "Masjid e dawoodia",
  "Masjid E Ibrahimia",
  "DARGA PEERANSHAHWALI RH",
  "Masjid Khursheed",
  "Masjid E Bisaheba",
  "Sri Abhayanjaneya Swamy Devasthanam  Srimad Virat Potuluri Veerabramhendra Swamy Temple",
  "K S Nagar Hanuman Temple",
  "Masjid E Abbu Hurera",
  "New Bhodraie",
  "Panchamukha Hanuman Temple Hanuman Nagar",
  "Bhulakshaamma Temple",
  "Sringeri Shankara Matam",
  "Masjid - E - Akbar",
  "hanuman temple(new)",
  "Hanuman TempleLalapet",
  "ASHOORKHANA E IMAM E QASIM",
  "Jama Masjid Chegur",
  "hanuman gundu",
  "Masjid e jaweedia",
  "Vaishnavi Mata Temple",
  "Sri Vara Siddhi Vinayaka Devalayam",
  "Konda Wwamy Ganeah Mamdapam",
  "Pochamma nagulu temple",
  "Maisigandi Maisamma temple",
  "Masjid Mohiuddin Pasha Qadri Zareen Kulah",
  "Masjid-e-Daire Nau",
  "Sri Adilakshmi Aluvelumanga Sametha Sri Venkateswara Swamy temple",
  "Shivam lodhi radhapur",
  "Sai Baba temple mungoad road",
  "Masjid -e- Ghaffaria",
  "Sri Ganapathi temple",
  "MASJID - E - SALEEM AMEER",
  "Sri Mallikarjuna Temple",
  "Masjid-E-Mohammadia",
  "Koneru Varaha Swamy Temple",
  "Yadagirigutta",
  "Sri Dattatreya Temple",
  "Sri Sri Pochamma Thalli Devalayam Ghatkesar Telangana",
  "Masjid e zahra",
  "Sri Prasan Anjaneya Swamy Temple",
  "Chinthalkunta",
  "Chiryala Lakshmi Narasimha Swamy Temple",
  "Sri Satyanarayana Swamy temple",
  "Moula Ali View Point",
  "Masjid-E-Noorani Addagutta",
  "Masjid-e-Khalifa Noor ul Hasnath",
  "Top Khana Masjid",
  "Adarsha Colony Anjaneyaswami Temple",
  "Jamia Masjid Musheerabad",
  "Masjid-e-Noorut Tawheed Ahle Hadees",
  "Masjid-e-Himayatsagar(TSERL)",
  "Gayatri Mata Satpati Palghar",
  "Masjid E Hafsah",
  "Shri Markandeya Swamy Devalayam",
  "Jamia masjid NOORANI",
  "Noorani Masjid",
  "Maisamma devalayam temple",
  "temple",
  "MASJID E KHAIR UNISA",
  "Masjid E Haroon Suraida",
  "Masjid Makaram",
  "Masjid -E-Qutub Shahi",
  "Masjid E Sahaba rz",
  "Chenna Keshava Swami Temple",
  "Masjid Shamsi",
  "SRI SHIVALAY TEMPLE",
  "Eidgah Dharur",
  "Venkateswara Premium Devasthanam",
  "Sri Nalla Pochamma Temple ChandranagarYakutpura",
  "Mahankali Pochamma Tample",
  "Jama Masjid Kalima",
  "Jama Masjid Wazeer Unnisa",
  "Hanuman Temple Bonthapally",
  "Ceremony puja",
  "Jamia Masjid-E-Noor",
  "Royal friends yoth",
  "Sri Mahankali Mandir",
  "Arulmigu Sri Veeranar Swamy Kovil",
  "Masjid-E-Elaahi",
  "Masjid e Haleema Be Saheba",
  "Bhu Lakshmamma Temple",
  "Masjid-e-shehzadi",
  "Khaankhaah Jamalia -Hazrat jamal-ur- Rahman Sahab",
  "Sri Jagdamba Matha  Sri Sevalal Maharaj Mandir Gollagudem Thanda",
  "Pochamma Talli Devalayam",
  "Sri BhoLaxmamma Thalli Devalayam",
  "Jagganath temple",
  "Masjid E Omer Frooq",
  "Masjid e Ameer ul khanam",
  "Sri Lalitha Devi Ammavaru",
  "Sri Katta Maisamma",
  "SAIDEEKSHA",
  "Masjid Shaikh Faisal",
  "Choti Masjid Qutubshahi",
  "Jama Masjid Asar-E-Sharif Rehmania",
  "Mata Vaishnavi Temple",
  "Sri Vijay Durga Temple",
  "Sri Ramalingeswara Temple",
  "Shr Gtha Bhawan",
  "SriSriSri mallelamma Maathali Devasthanam",
  "Jama e Masjid",
  "Ayyappa Swamy temple",
  "Sree Mallikarjuna Swamy Devasthanam Khajaguda",
  "Sri Bangaru Maisamma Alayam",
  "Sri Shiridi Sainadha Temple",
  "Hanuman Temple Gandipet",
  "Sri Beerappa swamy Temple",
  "Mahakali Temple",
  "Vittaleshwara Temple",
  "Lord Jaganath Temple",
  "Masjid E Maqbarah",
  "Masjid Hazrath Amina Begum Rehmatullah Alaiha",
  "Shri Vijaya Lakshmi Narasimha Swamy Temple",
  "Mahadev mandir",
  "Birthday gifts box in hyderabad",
  "OM Temple",
  "Sri Sri Durga Bhavani Temple",
  "Jama Masjid Qadria",
  "Sri Sankat Mochan Hanuman Temple",
  "Masjid-E-Shahamat Jung",
  "Masjid Naamdar Khan",
  "Sris Sri Sri shiridi sai baba temple",
  "Subhramanyeswara Swamy Devalayam",
  "Masjid-E-Hazrat Sayyadina Bilal RA",
  "Masjid E Firdous",
  "Masjid e tayyaba",
  "durga temple",
  "Nalla Pochamma Gudi",
  "Madhapur Hanuman mandir",
  "Shivaji youth",
  "BAJRANG FRIENDS YOUTH GANESH",
  "Masjid-e-Umar",
  "Masjid E Akbar",
  "Masjid E Ayesha",
  "Sri Bhangaru Pochamma temple",
  "Vigneswara Colony Marlu",
  "Mansanpally Shivalayam",
  "Venkateswara Temple",
  "Masjid E Noori",
  "Masjid Rail Enclave",
  "Eid Gaah MZK",
  "AUTONAGAR NEW MASJID",
  "Pochamma Temple Gemini Colony",
  "Venkateswara Visweswara Swamy Temple BHEL",
  "Honor i",
  "Kashibugga Shivalayam",
  "Sri NagaLakshmi Ammavari Temple",
  "RamNagar Siddiq Bhai Ganesh",
  "Masjid-e-Aamena",
  "Masjid E Hassan Basri",
  "Sri Sathya Sai Seva Sudha",
  "Ishta Kameshwari Temple",
  "Dhanush youth association",
  "SHIVAMMA NAGAR COLONY",
  "Jammi Chettu Durga Mandir",
  "Masjid E Noor E Elahi",
  "Venkateshwara temple",
  "Jama Masjid Kulsumpura Karwan (Badi Masjid)",
  "Simha Varahi Temple",
  "Siraj Unnisa Begum Saheba Masjid",
  "Masjid Fakhrunnisa Begum",
  "Sri VenkateswaraSwamy Devastanamu",
  "Masjid E Muhammadi Ahle Hadees",
  "Kasi Viswanath temple ( under construction)",
  "Dattatreya Temple",
  "Nani home",
  "Shri Kolhapuri Mahalaxmi Devalayam",
  "Lakshmi Narasimha Swamy Temple",
  "Ramkoti Masjid",
  "samakka sarakka temple",
  "Masjid-e-AbdulQawi Ahle Hadith",
  "Eidgah First Lancer",
  "Masjid Fatima Zehra",
  "Madinaguda Mosque",
  "shivalayam temple",
  "MUSLIUM GRAVEYARDS  DARGA HAZRATH SYED SAMAJ KHALE SHAWALI",
  "Lalaguda Jamia Masjid",
  "lakshminarasimhaswamy temple",
  "Sri Venugopala Swamy Devalayam",
  "Manikonda Hanuman Temple",
  "Chamudeshwari jothishlayam",
  "Masjid E Mustafa",
  "Bakthi Tarangini",
  "Masjid-e-Ek Minar Ahle Hadees",
  "Hanuman temple  jp darga road",
  "Masjid-e-shaik chand",
  "Dargha",
  "Ramachandraguda Shivalayam Mallikarjuna youth",
  "Maha Ganapathi",
  "Anjaneyulu Gudi",
  "EidGah  Muslim Grave yard",
  "Sadiq paradise",
  "Sai baba Temple",
  "Mohammedia street",
  "SHAFIQ MANZIL",
  "Masjid-e-Chandkhan",
  "Falaknuma Mallikarjuna Swamy Temple",
  "Kalyaana mantapam",
  "Jama Masjid Faluknana",
  "Laxmi mata mandir gol mazid feelkhana",
  "Temple Well",
  "Bhagyalakshmi Temple",
  "Masjid - E- Qutub Shahi",
  "Sri Rama temple",
  "APARNA Peddamma Temple",
  "PochamammTalli Temple",
  "Sri Vishnu Mandir",
  "Rinasdham",
  "Shiv mandir NISA",
  "Muslim Graveyard",
  "Sri Bhramaramba Devi Temple",
  "Shiva Parvati on Linga",
  "Laxminarayana Temple",
  "Sri Saibaba - Santhosi Alayam",
  "Saikumar",
  "peddamma temple",
  "Sree Sree Sree Mallikarjuna Swami Devastanam",
  "Sri Suryamukhi Hanuman Mandir",
  "Maisamma Temple N J R Colony Cheeriyal",
  "Mahankali Temple Chinna Cherlapally",
  "Sri Bhramagiri Shetram Gayatri Devalayam",
  "Durgamma TempleBongloor",
  "Sri Annapurna Devi Devalayamu",
  "venkateswara temple",
  "Sri Sai Sannidhi",
  "Sri pochamma devalayam kollur",
  "VSEWA GANESH MANDAPAM",
  "Hindu temple",
  "Pochamma Durgamma Temple",
  "Qabrasthan K R P Grave Yatd",
  "Pushamal Temple",
  "Samarth Narayan Gowshala",
  "Sri Hanuman Devalayam  Velimela Thanda",
  "Sri Peddamma Talli Devalayam",
  "Masjid-e-Qutubshahi",
  "IbadUrRahman Group of Islamic Institutions",
  "Srikari Peetam",
  "shivalayam",
  "Jama Masjid Chintal bazaar",
  "Masjid E MOMEEN",
  "honuman temple",
  "Hanuman Temple  Ranga Reddy Nagar",
  "Shiva Saibaba temple",
  "Masjid-e-madina",
  "JAMIA MASJID MOHAMMADI",
  "Dargha gouse-e-paak",
  "Anjaneya Swamy Devalayam",
  "Pochamma thail temple",
  "Masjid- E- Bagh",
  "DhanaLakshmi Swarna Mandir",
  "Srimatha Veda Vignanna Prachara Parishat",
  "Masjid-e-Aashique Ilahi",
  "Sri Naga Phaneendra temple",
  "Purani Masjid",
  "Karmanghat Qabrastan",
  "Sri Ranganayaka swamy Temple",
  "Tulsiram Hanuman Bagas Gilada",
  "saptamukhi veera hanuman temple",
  "Naag Mata Temple",
  "Sri Jagannath Mandir",
  "Masjid-E-Barq Jung",
  "Masjid E Rahmatulil Alameen",
  "Quwat Jung Mosque",
  "Hanuman Mandhir",
  "Masjid e Firdous Halqa Saroor Nagar Markaz",
  "Yellammaa TempleAlgole",
  "Gayathrinagar utasav",
  "Sri Vinayaka Swamy Devalayam",
  "Marri Pochamma Temple",
  "Bahuti makhopur",
  "Prasana anjaneya temple",
  "Masjid E Ameena Abdullah Nase",
  "Masjid e Arqam Ahle Hadees",
  "Kali matha statue",
  "Vijay hanuman youth association",
  "Masjid-e-Prince Shahamat Jah Bahadur",
  "Masjid E Paltan",
  "Kapade Daivam Ayyappa Sanidhanam",
  "Hindu small temple",
  "Siddhi Vinayaka Temple",
  "Gundalu - Machleshwar",
  "Jamia Umay Habiba lilbanat Al Islam",
  "Devathalamma Gudi Marrigudem",
  "Peddamma thalli gudi",
  "Katta Mysamma gudi",
  "Peddamma TempleMansoorabad",
  "Dhurgamma gudi",
  "Burhani Masjid",
  "SHRI SAI BABA MANDIR",
  "Durga Temple Devi Chowk",
  "Sant Sri Sadguru Keshav Swamy Maharaj Samadhi",
  "Masjid E Tawheed (Ahle Hadees)",
  "Sri Ramanjaneya Temple",
  "Masjid Mohammedia Tara Maidan",
  "Udaye Anna adda",
  "Darga Hazarat Syed asad ullah shah quadri mahelneknampur",
  "Sri Krishna Goshala",
  "Venkateshwara Balaji Temple",
  "Anjaneya swamy Temple",
  "Sai Baba temple Jaya darshini enclave kompally",
  "Sheriguda Mallanna Temple",
  "Masjid-e-ishatul Uloom",
  "Mohammadi Masjid",
  "Markaz Aiwan-e-Mohammadi",
  "Panchmukhi Hanuman Temple",
  "Sri Mallikarjuna Swamy Devastanam",
  "JAMA MASJID LEMOOR",
  "Masjid E Saleha Hafeez",
  "Madeenaguda Pochamma Talli Temple",
  "Alivelumanga Sametha Venkateshwara Swami Devalayam",
  "Gouranga mandal",
  "Madarsa",
  "Masjide E Ayesha",
  "Sri Kashi Vishweshwara Annapoorna Punyakhetram",
  "VENKATESHWARA SWAMY TEMPLE MANKHAL",
  "Sri prasanna venkateshwara swamy temple",
  "Masjid -e-Fauzia Mansoor Ahle Hadees",
  "Veerabhadra Swamy Temple",
  "bajrangbali Temple",
  "Mitthu",
  "Nukalgudem hanuman temple",
  "Pochamma Temple keesara",
  "Shri Swami Samarth Mandir",
  "lord shiva templenri township",
  "Massjed A OMER",
  "Jalaram Temple",
  "Kollur Jama Masjid",
  "Masjid Shahabia",
  "VENKATESWARASWAMY TEMPLE",
  "Masjid Gulzar E Madina",
  "Alamgir Masjid",
  "Sri Nakuleshwari Devi Peetham",
  "Sri Shivaganga Temple",
  "Mankhal Temple",
  "Jama masjid fruit matketkothapet Hyderabad",
  "JAMA MASJID AL-AZAM (Mosque)",
  "Maula Ali Car entry",
  "Dargah hazrat Syed Hassan Hussain Baba rahmatullah alayh",
  "MAREMMA YADI DEVALAYAM",
  "Sufi Ali pasha khanka-E-Qalandar",
  "Ismail Hussain Mosque",
  "Saleheen Masjid",
  "Masjid-e-Ibrahim",
  "Masjid E Shaik Omer",
  "KOTA GUTA Peddamma Temple Lalsahebguda Road"
];

module.exports = locations;
