package com.ubr.dcagapiservicejava.domain.enums;

public enum TaskCategory {

    NA, TEXT_TO_AUDIO, RECORD_AUDIO, UPLOAD_IMAGE, IMAGE_TO_TEXT, RECEIPT_DIGITIZATION, LOCALIZATION_QUALITY, IMAGE_LABELLING, MENU_PHOTO_REVIEW;
}
