export const tasks = [
    {
      "id": "101",
      "phone": "",
      "name": "ABC",
      "ratings": 3.4,
      "totalPoints": "",
      "tasks": [
        {
          "name": "Task1",
          "id": "1001",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Hyderabad",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task2",
          "id": "1002",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Pocharam",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task3",
          "id": "1003",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Mallapur",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task4",
          "id": "1004",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Kukatpally",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task5",
          "id": "1005",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Barkatpura",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task6",
          "id": "1006",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Nallagandla",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task7",
          "id": "1007",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Tiruvananthapuram",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task8",
          "id": "1008",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Choutuppal",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task9",
          "id": "1009",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Khairatabad",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task10",
          "id": "1010",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Sanathnagar",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task11",
          "id": "1011",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Bharat Nagar",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task12",
          "id": "1012",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Erragadda",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task13",
          "id": "1013",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Borabanda",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },

        {
          "name": "Task14",
          "id": "1014",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Moti Nagar",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task15",
          "id": "1015",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Secunderabad",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task16",
          "id": "1016",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Chilkalguda",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task17",
          "id": "1017",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Kavadiguda",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task18",
          "id": "1018",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "MG Road (James Street)",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task19",
          "id": "1019",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Madannapet",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task20",
          "id": "1020",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Minister Road",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task21",
          "id": "1021",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Mylargadda",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task22",
          "id": "1022",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Namalagundu",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task23",
          "id": "1023",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Padmarao Nagar",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task24",
          "id": "1024",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Pan bazar",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task25",
          "id": "1025",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Parsigutta",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task26",
          "id": "1026",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Patny",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task27",
          "id": "1027",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Rani Gunj",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task28",
          "id": "1028",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "RP Road",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task29",
          "id": "1029",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Sindhi Colony",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task30",
          "id": "1030",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Sitaphalmandi",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task31",
          "id": "1031",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Tarnaka",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task32",
          "id": "1032",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Warsiguda",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task33",
          "id": "1033",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Addagutta",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task34",
          "id": "1034",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Tukaramgate",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task35",
          "id": "1035",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Jubilee Hills",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },{
          "name": "Task36",
          "id": "1036",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Banjara Hills",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },{
          "name": "Task37",
          "id": "1037",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Film Nagar",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },{
          "name": "Task38",
          "id": "1038",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Yousufguda",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },{
          "name": "Task39",
          "id": "1039",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Srinagar colony",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },{
          "name": "Task40",
          "id": "1040",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Afzal Gunj",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task41",
          "id": "1041",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Aliabad",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task42",
          "id": "1042",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Alijah Kotla",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task43",
          "id": "1043",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Asif Nagar",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task44",
          "id": "1044",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Azampura",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task45",
          "id": "1045",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Barkas",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task46",
          "id": "1046",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Bazarghat",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task47",
          "id": "1047",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Begum Bazaar",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task48",
          "id": "1048",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Chaderghat",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        }
        ,{
          "name": "Task49",
          "id": "1049",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Chanchalguda",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },{
          "name": "Task50",
          "id": "1050",
          "pay": "2",
          "status": "new",
          "type": "Text to Audio",
          "taskDesc": "textToAudioTaskDesc",
          "input": "Chandrayan Gutta",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task51",
          "id": "1051",
          "pay": "2",
          "status": "new",
          "type": "Audio to Audio",
          "taskDesc": "audioToAudioTaskDesc",
          "input": "Guwahati.mp3",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task52",
          "id": "1052",
          "pay": "2",
          "status": "new",
          "type": "Audio to Audio",
          "taskDesc": "audioToAudioTaskDesc",
          "input": "Shillong.mp3",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task53",
          "id": "1053",
          "pay": "2",
          "status": "new",
          "type": "Audio to Audio",
          "taskDesc": "audioToAudioTaskDesc",
          "input": "Shirdi.mp3",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task54",
          "id": "1054",
          "pay": "2",
          "status": "new",
          "type": "Audio to Audio",
          "taskDesc": "audioToAudioTaskDesc",
          "input": "Vishakapatnam.mp3",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
        {
          "name": "Task55",
          "id": "1055",
          "pay": "2",
          "status": "new",
          "type": "Audio to Audio",
          "taskDesc": "audioToAudioTaskDesc",
          "input": "Madurai.mp3",
          "output": "",
          "startDate": "11/14/2023",
          "endDate": "11/15/2023",
          "audioSavedId":""
        },
      ]
    }
  ]