export const tasks = [
    {
      "id": "101",
      "phone": "8686478524",
      "name": "sameer mishra",
      "ratings": 3.4,
      "totalPoints": "",
      "tasks": [
        {
          "name": "Task1",
          "id": "101",
          "pay": "200",
          "status": "new",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "pronounce hyderabad",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task2",
          "id": "102",
          "pay": "200",
          "status": "new",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "pronounce hyderabad",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task3",
          "id": "103",
          "pay": "200",
          "status": "new",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "pronounce Bengaluru",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        
        {
          "name": "Task4",
          "id": "104",
          "pay": "200",
          "status": "new",
          "type": "Audio to audio",
          "taskDesc": "Record audio by listening audio and earn in no time.",
          "input": "http://localhost:8000/audio/audio-clip-task-104.wav",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task5",
          "id": "105",
          "pay": "200",
          "status": "new",
          "type": "Audio to audio",
          "taskDesc": "Record audio by listening audio and earn in no time.",
          "input": "http://localhost:8000/audio/audio-clip-task-105.wav",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task6",
          "id": "106",
          "pay": "200",
          "status": "new",
          "type": "Audio to audio",
          "taskDesc": "Record audio by listening audio and earn in no time.",
          "input": "http://localhost:8000/audio/audio-clip-task-106.wav",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task7",
          "id": "107",
          "pay": "200",
          "status": "In Progress",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "Pronounce Bengaluru",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task8",
          "id": "108",
          "pay": "200",
          "status": "In Progress",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "Pronounce Bengaluru",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task9",
          "id": "109",
          "pay": "200",
          "status": "In Progress",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "Pronounce Hyderabad",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task10",
          "id": "110",
          "pay": "200",
          "status": "In Progress",
          "type": "Audio to audio",
          "taskDesc": "Record audio by listening audio and earn in no time.",
          "input": "",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task11",
          "id": "111",
          "pay": "200",
          "status": "In Progress",
          "type": "Audio to audio",
          "taskDesc": "Record audio by listening audio and earn in no time.",
          "input": "",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task12",
          "id": "112",
          "pay": "200",
          "status": "In Progress",
          "type": "Audio to audio",
          "taskDesc": "Record audio by listening audio and earn in no time.",
          "input": "",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task13",
          "id": "113",
          "pay": "200",
          "status": "Completed",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "pronounce hyderabad",
          "output": "http://localhost:8000/audio/113",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task14",
          "id": "114",
          "pay": "200",
          "status": "Completed",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "Pronounce Bengaluru",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task15",
          "id": "115",
          "pay": "200",
          "status": "Completed",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "pronounce Hyderabad",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task16",
          "id": "116",
          "pay": "200",
          "status": "Completed",
          "type": "Audio to audio",
          "taskDesc": "Record audio by listening audio and earn in no time.",
          "input": "pronounce Hyderabad",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task17",
          "id": "117",
          "pay": "200",
          "status": "Completed",
          "type": "Audio to audio",
          "taskDesc": "Record audio by listening audio and earn in no time.",
          "input": "Hyderabad",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task18",
          "id": "118",
          "pay": "200",
          "status": "Completed",
          "type": "Audio to audio",
          "taskDesc": "Record audio by listening audio and earn in no time.",
          "input": "Hyderabad",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task19",
          "id": "119",
          "pay": "200",
          "status": "Blocked",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "Hyderabad",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task20",
          "id": "120",
          "pay": "200",
          "status": "Blocked",
          "type": "Text to audio",
          "taskDesc": "Record audio of text and earn in no time.",
          "input": "Hyderabad",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        },
        {
          "name": "Task21",
          "id": "121",
          "pay": "200",
          "status": "Blocked",
          "type": "Audio to audio",
          "taskDesc": "Record audio by listening audio and earn in no time.",
          "input": "Hyderabad",
          "output": "",
          "startDate": "12/10/2023 ",
          "endDate": "15/10/ 2023"
        }
      ]
    }
  ]