spring:
  cloud:
    gcp:
      project-id: anz-driver-ops-ritu
#      firestore:
#        database-id: dcag
#        credentials:
#          location: classpath:anz-driver-ops-ritu-f53a0fa0d07e.json


